<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Replaces all questions with a curated set of real trivia covering the
 * Netherlands, Sweden and Croatia. `correct_option` only supports a single
 * answer (enum A-D), so source questions that had multiple correct answers
 * were rephrased into single-answer equivalents (e.g. "which of these is
 * NOT...") rather than dropped.
 */
class QuestionSeeder extends Seeder
{
    use WithoutModelEvents;

    private const TIME_LIMITS = [
        'easy' => 15,
        'medium' => 20,
        'hard' => 25,
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Question::query()->delete();

        foreach ($this->questions() as $question) {
            Question::create([
                'question_text' => $question['question_text'],
                'option_a' => $question['option_a'],
                'option_b' => $question['option_b'],
                'option_c' => $question['option_c'],
                'option_d' => $question['option_d'],
                'correct_option' => $question['correct_option'],
                'category' => $question['category'],
                'country' => $question['country'],
                'difficulty' => $question['difficulty'],
                'time_limit_seconds' => self::TIME_LIMITS[$question['difficulty']],
            ]);
        }
    }

    /**
     * @return array<int, array{question_text: array<string, string>, option_a: array<string, string>, option_b: array<string, string>, option_c: array<string, string>, option_d: array<string, string>, correct_option: string, category: string, country: string, difficulty: string}>
     */
    private function questions(): array
    {
        return [
            ...$this->netherlandsQuestions(),
            ...$this->swedenQuestions(),
            ...$this->croatiaQuestions(),
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function netherlandsQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'How many cities are there in the Netherlands?', 'nl' => 'Hoeveel steden zijn er in Nederland?'],
                'option_a' => ['en' => '100', 'nl' => '100'],
                'option_b' => ['en' => '220', 'nl' => '220'],
                'option_c' => ['en' => '350', 'nl' => '350'],
                'option_d' => ['en' => '500', 'nl' => '500'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Who is the King of the Netherlands?', 'nl' => 'Wie is de koning van Nederland?'],
                'option_a' => ['en' => 'Willem-Alexander', 'nl' => 'Willem-Alexander'],
                'option_b' => ['en' => 'Beatrix', 'nl' => 'Beatrix'],
                'option_c' => ['en' => 'Alexander', 'nl' => 'Alexander'],
                'option_d' => ['en' => 'Philippe', 'nl' => 'Filip'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which dish is typically Dutch?', 'nl' => 'Welk gerecht is typisch Nederlands?'],
                'option_a' => ['en' => 'Stamppot', 'nl' => 'Stamppot'],
                'option_b' => ['en' => 'Paella', 'nl' => 'Paella'],
                'option_c' => ['en' => 'Sushi', 'nl' => 'Sushi'],
                'option_d' => ['en' => 'Tacos', 'nl' => 'Tacos'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the capital of the Netherlands?', 'nl' => 'Wat is de hoofdstad van Nederland?'],
                'option_a' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam'],
                'option_b' => ['en' => 'The Hague', 'nl' => 'Den Haag'],
                'option_c' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam'],
                'option_d' => ['en' => 'Utrecht', 'nl' => 'Utrecht'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the official currency of the Netherlands?', 'nl' => 'Wat is de officiële munteenheid van Nederland?'],
                'option_a' => ['en' => 'Euro', 'nl' => 'Euro'],
                'option_b' => ['en' => 'Guilder', 'nl' => 'Gulden'],
                'option_c' => ['en' => 'Dollar', 'nl' => 'Dollar'],
                'option_d' => ['en' => 'Pound', 'nl' => 'Pond'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which flower is the Netherlands most famous for worldwide?', 'nl' => 'Welke bloem is Nederland wereldwijd het meest bekend voor?'],
                'option_a' => ['en' => 'Tulip', 'nl' => 'Tulp'],
                'option_b' => ['en' => 'Rose', 'nl' => 'Roos'],
                'option_c' => ['en' => 'Sunflower', 'nl' => 'Zonnebloem'],
                'option_d' => ['en' => 'Lily', 'nl' => 'Lelie'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'What was Amsterdam historically famous for cutting?', 'nl' => 'Waar was Amsterdam historisch beroemd voor het slijpen van?'],
                'option_a' => ['en' => 'Diamonds', 'nl' => 'Diamanten'],
                'option_b' => ['en' => 'Gold', 'nl' => 'Goud'],
                'option_c' => ['en' => 'Silver', 'nl' => 'Zilver'],
                'option_d' => ['en' => 'Glass', 'nl' => 'Glas'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which traditional structure was used to pump water away?', 'nl' => 'Welk traditioneel bouwwerk werd gebruikt om water weg te pompen?'],
                'option_a' => ['en' => 'Windmill', 'nl' => 'Molen'],
                'option_b' => ['en' => 'Castle', 'nl' => 'Kasteel'],
                'option_c' => ['en' => 'Tower', 'nl' => 'Toren'],
                'option_d' => ['en' => 'Dike', 'nl' => 'Dijk'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which cheese variety is known worldwide as Dutch?', 'nl' => 'Welke kaassoort is wereldwijd bekend als Nederlands?'],
                'option_a' => ['en' => 'Gouda', 'nl' => 'Goudse kaas'],
                'option_b' => ['en' => 'Brie', 'nl' => 'Brie'],
                'option_c' => ['en' => 'Cheddar', 'nl' => 'Cheddar'],
                'option_d' => ['en' => 'Parmesan', 'nl' => 'Parmezaan'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Dutch painter made "The Night Watch"?', 'nl' => 'Welke Nederlandse schilder maakte "De Nachtwacht"?'],
                'option_a' => ['en' => 'Rembrandt van Rijn', 'nl' => 'Rembrandt van Rijn'],
                'option_b' => ['en' => 'Vincent van Gogh', 'nl' => 'Vincent van Gogh'],
                'option_c' => ['en' => 'Johannes Vermeer', 'nl' => 'Johannes Vermeer'],
                'option_d' => ['en' => 'Piet Mondriaan', 'nl' => 'Piet Mondriaan'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which city is the International Court of Justice located?', 'nl' => 'In welke stad zit het Internationaal Gerechtshof?'],
                'option_a' => ['en' => 'The Hague', 'nl' => 'Den Haag'],
                'option_b' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam'],
                'option_c' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam'],
                'option_d' => ['en' => 'Utrecht', 'nl' => 'Utrecht'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Dutch island does not belong to the Wadden Islands?', 'nl' => 'Welk Nederlands eiland behoort niet tot de Waddeneilanden?'],
                'option_a' => ['en' => 'Texel', 'nl' => 'Texel'],
                'option_b' => ['en' => 'Terschelling', 'nl' => 'Terschelling'],
                'option_c' => ['en' => 'Ameland', 'nl' => 'Ameland'],
                'option_d' => ['en' => 'Walcheren', 'nl' => 'Walcheren'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the traditional Dutch wooden shoe called?', 'nl' => 'Wat is de traditionele Nederlandse houten schoen genaamd?'],
                'option_a' => ['en' => 'Klomp', 'nl' => 'Klomp'],
                'option_b' => ['en' => 'Beanie', 'nl' => 'Muts'],
                'option_c' => ['en' => 'Scarf', 'nl' => 'Sjaal'],
                'option_d' => ['en' => 'Cap', 'nl' => 'Pet'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which Dutch city is the famous Van Gogh Museum located?', 'nl' => 'In welke Nederlandse stad staat het beroemde Van Gogh Museum?'],
                'option_a' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam'],
                'option_b' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam'],
                'option_c' => ['en' => 'Utrecht', 'nl' => 'Utrecht'],
                'option_d' => ['en' => 'Eindhoven', 'nl' => 'Eindhoven'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the best-known Dutch beer producer?', 'nl' => 'Wat is de bekendste Nederlandse bierproducent?'],
                'option_a' => ['en' => 'Heineken', 'nl' => 'Heineken'],
                'option_b' => ['en' => 'Grolsch', 'nl' => 'Grolsch'],
                'option_c' => ['en' => 'Amstel', 'nl' => 'Amstel'],
                'option_d' => ['en' => 'Bavaria', 'nl' => 'Bavaria'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which sea borders the Netherlands to the north and west?', 'nl' => 'Welke zee grenst aan Nederland in het noorden en westen?'],
                'option_a' => ['en' => 'North Sea', 'nl' => 'Noordzee'],
                'option_b' => ['en' => 'Baltic Sea', 'nl' => 'Oostzee'],
                'option_c' => ['en' => 'Mediterranean Sea', 'nl' => 'Middellandse Zee'],
                'option_d' => ['en' => 'Irish Sea', 'nl' => 'Ierse Zee'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the Dutch word for "cheers" when toasting?', 'nl' => 'Wat is het Nederlandse woord voor "cheers" bij het proosten?'],
                'option_a' => ['en' => 'Proost', 'nl' => 'Proost'],
                'option_b' => ['en' => 'Skål', 'nl' => 'Skål'],
                'option_c' => ['en' => 'Cin cin', 'nl' => 'Cin cin'],
                'option_d' => ['en' => 'Salud', 'nl' => 'Salud'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the highest point on the Dutch mainland?', 'nl' => 'Wat is het hoogste punt van het Nederlandse vasteland?'],
                'option_a' => ['en' => 'Vaalserberg', 'nl' => 'Vaalserberg'],
                'option_b' => ['en' => 'Mont Blanc', 'nl' => 'Mont Blanc'],
                'option_c' => ['en' => 'Zugspitze', 'nl' => 'Zugspitze'],
                'option_d' => ['en' => 'Ben Nevis', 'nl' => 'Ben Nevis'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'In which year did the Netherlands gain independence from Spain (Peace of Münster)?', 'nl' => 'In welk jaar werd Nederland onafhankelijk van Spanje (Vrede van Münster)?'],
                'option_a' => ['en' => '1568', 'nl' => '1568'],
                'option_b' => ['en' => '1648', 'nl' => '1648'],
                'option_c' => ['en' => '1815', 'nl' => '1815'],
                'option_d' => ['en' => '1830', 'nl' => '1830'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which famous Dutch event involves skating long distances along frozen canals past eleven cities?', 'nl' => 'Welk beroemd Nederlands evenement bestaat uit schaatsen langs elf steden over bevroren kanalen?'],
                'option_a' => ['en' => 'Elfstedentocht', 'nl' => 'Elfstedentocht'],
                'option_b' => ['en' => 'Formula 1', 'nl' => 'Formule 1'],
                'option_c' => ['en' => 'Cricket', 'nl' => 'Cricket'],
                'option_d' => ['en' => 'Rugby', 'nl' => 'Rugby'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Dutch province is home to the city of Maastricht?', 'nl' => 'In welke Nederlandse provincie ligt de stad Maastricht?'],
                'option_a' => ['en' => 'Limburg', 'nl' => 'Limburg'],
                'option_b' => ['en' => 'Groningen', 'nl' => 'Groningen'],
                'option_c' => ['en' => 'Zeeland', 'nl' => 'Zeeland'],
                'option_d' => ['en' => 'Friesland', 'nl' => 'Friesland'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'A large part of the Netherlands lies below what?', 'nl' => 'Een groot deel van Nederland ligt onder wat?'],
                'option_a' => ['en' => 'Sea level', 'nl' => 'Zeeniveau'],
                'option_b' => ['en' => 'Cloud level', 'nl' => 'Wolkenniveau'],
                'option_c' => ['en' => 'Mountain level', 'nl' => 'Bergniveau'],
                'option_d' => ['en' => 'Snow level', 'nl' => 'Sneeuwniveau'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Who led the Dutch Revolt against Spain as the first Prince of Orange?', 'nl' => 'Wie leidde de Nederlandse Opstand tegen Spanje als eerste Prins van Oranje?'],
                'option_a' => ['en' => 'William the Silent', 'nl' => 'Willem van Oranje'],
                'option_b' => ['en' => 'Maurice of Nassau', 'nl' => 'Maurits van Nassau'],
                'option_c' => ['en' => 'William III', 'nl' => 'Willem III'],
                'option_d' => ['en' => 'Johan de Witt', 'nl' => 'Johan de Witt'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Dutch artist pioneered the geometric abstraction of the De Stijl movement?', 'nl' => 'Welke Nederlandse kunstenaar was een pionier van de geometrische abstractie van De Stijl?'],
                'option_a' => ['en' => 'Piet Mondriaan', 'nl' => 'Piet Mondriaan'],
                'option_b' => ['en' => 'Rembrandt van Rijn', 'nl' => 'Rembrandt van Rijn'],
                'option_c' => ['en' => 'Johannes Vermeer', 'nl' => 'Johannes Vermeer'],
                'option_d' => ['en' => 'M.C. Escher', 'nl' => 'M.C. Escher'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the name of the large flood protection system built after the 1953 North Sea flood?', 'nl' => 'Wat is de naam van het grote waterkeringssysteem dat werd gebouwd na de watersnoodramp van 1953?'],
                'option_a' => ['en' => 'Delta Works', 'nl' => 'Deltawerken'],
                'option_b' => ['en' => 'Berlin Wall', 'nl' => 'Berlijnse Muur'],
                'option_c' => ['en' => 'Hoover Dam', 'nl' => 'Hoover Dam'],
                'option_d' => ['en' => 'Thames Barrier', 'nl' => 'Thames Barrier'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function swedenQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'What is the capital of Sweden?'],
                'option_a' => ['en' => 'Malmö'],
                'option_b' => ['en' => 'Stockholm'],
                'option_c' => ['en' => 'Gothenburg'],
                'option_d' => ['en' => 'Uppsala'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which country shares a land border with Sweden?'],
                'option_a' => ['en' => 'Norway'],
                'option_b' => ['en' => 'Denmark'],
                'option_c' => ['en' => 'Germany'],
                'option_d' => ['en' => 'Poland'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is a traditional Swedish food?'],
                'option_a' => ['en' => 'Paella'],
                'option_b' => ['en' => 'Köttbullar'],
                'option_c' => ['en' => 'Sushi'],
                'option_d' => ['en' => 'Tacos'],
                'correct_option' => 'B',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What color is the cross on the Swedish flag?'],
                'option_a' => ['en' => 'Yellow'],
                'option_b' => ['en' => 'Red'],
                'option_c' => ['en' => 'White'],
                'option_d' => ['en' => 'Black'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is "fika" in Sweden?'],
                'option_a' => ['en' => 'A coffee break'],
                'option_b' => ['en' => 'A national holiday'],
                'option_c' => ['en' => 'A type of dance'],
                'option_d' => ['en' => 'A winter sport'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "Which of these is Sweden's largest island?"],
                'option_a' => ['en' => 'Gotland'],
                'option_b' => ['en' => 'Öland'],
                'option_c' => ['en' => 'Bornholm'],
                'option_d' => ['en' => 'Åland'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which city is connected to Copenhagen by the Öresund Bridge?'],
                'option_a' => ['en' => 'Stockholm'],
                'option_b' => ['en' => 'Malmö'],
                'option_c' => ['en' => 'Gothenburg'],
                'option_d' => ['en' => 'Lund'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these people is NOT Swedish?'],
                'option_a' => ['en' => 'Alfred Nobel'],
                'option_b' => ['en' => 'Anders Celsius'],
                'option_c' => ['en' => 'Carl Linnaeus'],
                'option_d' => ['en' => 'Isaac Newton'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which political party leads Sweden's government?"],
                'option_a' => ['en' => 'Moderaterna'],
                'option_b' => ['en' => 'Socialdemokraterna'],
                'option_c' => ['en' => 'Sverigedemokraterna'],
                'option_d' => ['en' => 'Liberalerna'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which of these is NOT a common feature of Sweden's landscape?"],
                'option_a' => ['en' => 'Forests'],
                'option_b' => ['en' => 'Lakes'],
                'option_c' => ['en' => 'Mountains'],
                'option_d' => ['en' => 'Deserts'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Swedish king was killed at the Battle of Lützen in 1632?'],
                'option_a' => ['en' => 'Charles XII'],
                'option_b' => ['en' => 'Gustav II Adolf'],
                'option_c' => ['en' => 'Gustav Vasa'],
                'option_d' => ['en' => 'Oscar II'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these was NOT ceded to Sweden under the Treaty of Roskilde (1658)?'],
                'option_a' => ['en' => 'Scania'],
                'option_b' => ['en' => 'Blekinge'],
                'option_c' => ['en' => 'Bohuslän'],
                'option_d' => ['en' => 'Gotland'],
                'correct_option' => 'D',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => "What is Sweden's highest mountain?"],
                'option_a' => ['en' => 'Kebnekaise'],
                'option_b' => ['en' => 'Helags'],
                'option_c' => ['en' => 'Åreskutan'],
                'option_d' => ['en' => 'Sarektjåkkå'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT a Swedish lake?'],
                'option_a' => ['en' => 'Vänern'],
                'option_b' => ['en' => 'Vättern'],
                'option_c' => ['en' => 'Mälaren'],
                'option_d' => ['en' => 'Lake Geneva'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which year did the warship Vasa sink?'],
                'option_a' => ['en' => '1523'],
                'option_b' => ['en' => '1628'],
                'option_c' => ['en' => '1709'],
                'option_d' => ['en' => '1814'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the second-largest city in Sweden?'],
                'option_a' => ['en' => 'Malmö'],
                'option_b' => ['en' => 'Gothenburg'],
                'option_c' => ['en' => 'Uppsala'],
                'option_d' => ['en' => 'Örebro'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which furniture retailer is a famous Swedish brand known worldwide?'],
                'option_a' => ['en' => 'IKEA'],
                'option_b' => ['en' => 'Walmart'],
                'option_c' => ['en' => 'Target'],
                'option_d' => ['en' => 'Argos'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "Which animal is considered a symbol of Sweden's forests?"],
                'option_a' => ['en' => 'Moose (elk)'],
                'option_b' => ['en' => 'Lion'],
                'option_c' => ['en' => 'Eagle'],
                'option_d' => ['en' => 'Bear'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Swedish pop group won Eurovision in 1974 with "Waterloo"?'],
                'option_a' => ['en' => 'ABBA'],
                'option_b' => ['en' => 'Roxette'],
                'option_c' => ['en' => 'Ace of Base'],
                'option_d' => ['en' => 'Europe'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "What is the name of Sweden's Arctic region, known for the midnight sun?"],
                'option_a' => ['en' => 'Lapland'],
                'option_b' => ['en' => 'Provence'],
                'option_c' => ['en' => 'Bavaria'],
                'option_d' => ['en' => 'Tuscany'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Swedish nobleman traditionally founded Stockholm in 1252?'],
                'option_a' => ['en' => 'Birger Jarl'],
                'option_b' => ['en' => 'Gustav Vasa'],
                'option_c' => ['en' => 'Charles XII'],
                'option_d' => ['en' => 'Carl XVI Gustaf'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "What is the largest land carnivore living in Sweden's wild?"],
                'option_a' => ['en' => 'Brown bear'],
                'option_b' => ['en' => 'Tiger'],
                'option_c' => ['en' => 'Lion'],
                'option_d' => ['en' => 'Jaguar'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which 1709 battle did Sweden suffer a decisive defeat to Russia under Peter the Great?'],
                'option_a' => ['en' => 'Battle of Poltava'],
                'option_b' => ['en' => 'Battle of Narva'],
                'option_c' => ['en' => 'Battle of Lützen'],
                'option_d' => ['en' => 'Battle of Waterloo'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Swedish author created the character Pippi Longstocking?'],
                'option_a' => ['en' => 'Astrid Lindgren'],
                'option_b' => ['en' => 'Stieg Larsson'],
                'option_c' => ['en' => 'Henning Mankell'],
                'option_d' => ['en' => 'Selma Lagerlöf'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the name of the strait separating southern Sweden from Denmark?'],
                'option_a' => ['en' => 'Öresund'],
                'option_b' => ['en' => 'Bosphorus'],
                'option_c' => ['en' => 'Strait of Gibraltar'],
                'option_d' => ['en' => 'English Channel'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function croatiaQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'What is the capital of Croatia?'],
                'option_a' => ['en' => 'Split'],
                'option_b' => ['en' => 'Zagreb'],
                'option_c' => ['en' => 'Rijeka'],
                'option_d' => ['en' => 'Osijek'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these does NOT share a land border with Croatia?'],
                'option_a' => ['en' => 'Slovenia'],
                'option_b' => ['en' => 'Hungary'],
                'option_c' => ['en' => 'Serbia'],
                'option_d' => ['en' => 'Italy'],
                'correct_option' => 'D',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is a traditional Croatian food?'],
                'option_a' => ['en' => 'Paella'],
                'option_b' => ['en' => 'Ćevapi'],
                'option_c' => ['en' => 'Sushi'],
                'option_d' => ['en' => 'Tacos'],
                'correct_option' => 'B',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which color is NOT on the Croatian flag?'],
                'option_a' => ['en' => 'Red'],
                'option_b' => ['en' => 'White'],
                'option_c' => ['en' => 'Blue'],
                'option_d' => ['en' => 'Green'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is "kava" most commonly associated with in Croatia?'],
                'option_a' => ['en' => 'A coffee break / social ritual'],
                'option_b' => ['en' => 'A national holiday'],
                'option_c' => ['en' => 'A type of dance'],
                'option_d' => ['en' => 'A winter sport'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT a Croatian island?'],
                'option_a' => ['en' => 'Hvar'],
                'option_b' => ['en' => 'Brač'],
                'option_c' => ['en' => 'Korčula'],
                'option_d' => ['en' => 'Capri'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which city is a major Adriatic port connected to Italy by regular ferry?'],
                'option_a' => ['en' => 'Zagreb'],
                'option_b' => ['en' => 'Rijeka'],
                'option_c' => ['en' => 'Osijek'],
                'option_d' => ['en' => 'Varaždin'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these people is NOT Croatian?'],
                'option_a' => ['en' => 'Nikola Tesla'],
                'option_b' => ['en' => 'Ruđer Bošković'],
                'option_c' => ['en' => 'Marco Polo'],
                'option_d' => ['en' => 'Isaac Newton'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these has been a major political party in Croatian politics?'],
                'option_a' => ['en' => 'HDZ'],
                'option_b' => ['en' => 'SDP'],
                'option_c' => ['en' => 'Most'],
                'option_d' => ['en' => 'All of the above'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which of these is NOT a common feature of Croatia's landscape?"],
                'option_a' => ['en' => 'Forests'],
                'option_b' => ['en' => 'Lakes'],
                'option_c' => ['en' => 'Mountains'],
                'option_d' => ['en' => 'Deserts'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which king is traditionally considered the first king of Croatia?'],
                'option_a' => ['en' => 'Tomislav'],
                'option_b' => ['en' => 'Zvonimir'],
                'option_c' => ['en' => 'Petar Krešimir IV'],
                'option_d' => ['en' => 'Petar Svačić'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these territories were historically significant parts of the Croatian lands?'],
                'option_a' => ['en' => 'Dalmatia'],
                'option_b' => ['en' => 'Slavonia'],
                'option_c' => ['en' => 'Istria'],
                'option_d' => ['en' => 'All of the above'],
                'correct_option' => 'D',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => "What is Croatia's highest mountain?"],
                'option_a' => ['en' => 'Dinara'],
                'option_b' => ['en' => 'Velebit'],
                'option_c' => ['en' => 'Biokovo'],
                'option_d' => ['en' => 'Risnjak'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT located in Croatia?'],
                'option_a' => ['en' => 'Vransko Lake'],
                'option_b' => ['en' => 'Plitvice Lakes'],
                'option_c' => ['en' => 'Lake Peruća'],
                'option_d' => ['en' => 'Lake Geneva'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which year did Croatia declare independence from Yugoslavia?'],
                'option_a' => ['en' => '1989'],
                'option_b' => ['en' => '1991'],
                'option_c' => ['en' => '1995'],
                'option_d' => ['en' => '2000'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which sea borders Croatia?'],
                'option_a' => ['en' => 'Adriatic Sea'],
                'option_b' => ['en' => 'Baltic Sea'],
                'option_c' => ['en' => 'Black Sea'],
                'option_d' => ['en' => 'North Sea'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "What is Croatia's official currency?"],
                'option_a' => ['en' => 'Euro'],
                'option_b' => ['en' => 'Kuna'],
                'option_c' => ['en' => 'Lira'],
                'option_d' => ['en' => 'Dinar'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Croatian city is known as the "Pearl of the Adriatic"?'],
                'option_a' => ['en' => 'Dubrovnik'],
                'option_b' => ['en' => 'Split'],
                'option_c' => ['en' => 'Zadar'],
                'option_d' => ['en' => 'Pula'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Croatian national park is famous for its terraced lakes and waterfalls?'],
                'option_a' => ['en' => 'Plitvice Lakes National Park'],
                'option_b' => ['en' => 'Serengeti National Park'],
                'option_c' => ['en' => 'Yosemite National Park'],
                'option_d' => ['en' => 'Fjordland National Park'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Roman emperor was born near Split and built a famous palace there?'],
                'option_a' => ['en' => 'Diocletian'],
                'option_b' => ['en' => 'Julius Caesar'],
                'option_c' => ['en' => 'Nero'],
                'option_d' => ['en' => 'Constantine'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which everyday item of clothing is said to derive its name from Croatian soldiers ("Hrvat")?'],
                'option_a' => ['en' => 'The necktie (cravat)'],
                'option_b' => ['en' => 'The umbrella'],
                'option_c' => ['en' => 'The wristwatch'],
                'option_d' => ['en' => 'The button'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Croatian peninsula region is known for truffles and wine?'],
                'option_a' => ['en' => 'Istria'],
                'option_b' => ['en' => 'Slavonia'],
                'option_c' => ['en' => 'Dalmatia'],
                'option_d' => ['en' => 'Zagorje'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Croatia was a republic within which federation from 1945 to 1991?'],
                'option_a' => ['en' => 'Yugoslavia'],
                'option_b' => ['en' => 'Soviet Union'],
                'option_c' => ['en' => 'Austro-Hungarian Empire'],
                'option_d' => ['en' => 'Ottoman Empire'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Croatian tennis player won the Wimbledon singles title in 2001?'],
                'option_a' => ['en' => 'Goran Ivanišević'],
                'option_b' => ['en' => 'Rafael Nadal'],
                'option_c' => ['en' => 'Novak Djokovic'],
                'option_d' => ['en' => 'Roger Federer'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What are the famous waterfalls on the Krka river known as?'],
                'option_a' => ['en' => 'Skradinski Buk'],
                'option_b' => ['en' => 'Niagara Falls'],
                'option_c' => ['en' => 'Victoria Falls'],
                'option_d' => ['en' => 'Angel Falls'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
        ];
    }
}
