<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Replaces all questions with a curated set of real trivia covering the
 * Netherlands, Sweden and Croatia. `correct_option` only supports a single
 * answer (enum A-D), so source questions that had multiple correct answers
 * were rephrased into single-answer equivalents (e.g. "which of these is
 * NOT...") rather than dropped.
 */
class QuestionSeeder extends Seeder
{
    use WithoutModelEvents;

    private const TIME_LIMITS = [
        'easy' => 15,
        'medium' => 20,
        'hard' => 25,
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Question::query()->delete();

        foreach ($this->questions() as $question) {
            Question::create([
                'question_text' => $question['question_text'],
                'option_a' => $question['option_a'],
                'option_b' => $question['option_b'],
                'option_c' => $question['option_c'],
                'option_d' => $question['option_d'],
                'correct_option' => $question['correct_option'],
                'category' => $question['category'],
                'country' => $question['country'],
                'difficulty' => $question['difficulty'],
                'time_limit_seconds' => self::TIME_LIMITS[$question['difficulty']],
            ]);
        }
    }

    /**
     * @return array<int, array{question_text: array<string, string>, option_a: array<string, string>, option_b: array<string, string>, option_c: array<string, string>, option_d: array<string, string>, correct_option: string, category: string, country: string, difficulty: string}>
     */
    private function questions(): array
    {
        return [
            ...$this->netherlandsQuestions(),
            ...$this->swedenQuestions(),
            ...$this->croatiaQuestions(),
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function netherlandsQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'How many cities are there in the Netherlands?', 'nl' => 'Hoeveel steden zijn er in Nederland?', 'hr' => 'Koliko gradova ima u Nizozemskoj?', 'se' => 'Hur många städer finns det i Nederländerna?'],
                'option_a' => ['en' => '100', 'nl' => '100', 'hr' => '100', 'se' => '100'],
                'option_b' => ['en' => '220', 'nl' => '220', 'hr' => '220', 'se' => '220'],
                'option_c' => ['en' => '350', 'nl' => '350', 'hr' => '350', 'se' => '350'],
                'option_d' => ['en' => '500', 'nl' => '500', 'hr' => '500', 'se' => '500'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Who is the King of the Netherlands?', 'nl' => 'Wie is de koning van Nederland?', 'hr' => 'Tko je kralj Nizozemske?', 'se' => 'Vem är Nederländernas kung?'],
                'option_a' => ['en' => 'Willem-Alexander', 'nl' => 'Willem-Alexander', 'hr' => 'Willem-Alexander', 'se' => 'Willem-Alexander'],
                'option_b' => ['en' => 'Beatrix', 'nl' => 'Beatrix', 'hr' => 'Beatrix', 'se' => 'Beatrix'],
                'option_c' => ['en' => 'Alexander', 'nl' => 'Alexander', 'hr' => 'Aleksandar', 'se' => 'Alexander'],
                'option_d' => ['en' => 'Philippe', 'nl' => 'Filip', 'hr' => 'Filip', 'se' => 'Filip'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which dish is typically Dutch?', 'nl' => 'Welk gerecht is typisch Nederlands?', 'hr' => 'Koje jelo je tipično nizozemsko?', 'se' => 'Vilken rätt är typiskt nederländsk?'],
                'option_a' => ['en' => 'Stamppot', 'nl' => 'Stamppot', 'hr' => 'Stamppot', 'se' => 'Stamppot'],
                'option_b' => ['en' => 'Paella', 'nl' => 'Paella', 'hr' => 'Paella', 'se' => 'Paella'],
                'option_c' => ['en' => 'Sushi', 'nl' => 'Sushi', 'hr' => 'Sushi', 'se' => 'Sushi'],
                'option_d' => ['en' => 'Tacos', 'nl' => 'Tacos', 'hr' => 'Tacos', 'se' => 'Tacos'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the capital of the Netherlands?', 'nl' => 'Wat is de hoofdstad van Nederland?', 'hr' => 'Koji je glavni grad Nizozemske?', 'se' => 'Vad är Nederländernas huvudstad?'],
                'option_a' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam', 'hr' => 'Amsterdam', 'se' => 'Amsterdam'],
                'option_b' => ['en' => 'The Hague', 'nl' => 'Den Haag', 'hr' => 'Haag', 'se' => 'Haag'],
                'option_c' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam', 'hr' => 'Rotterdam', 'se' => 'Rotterdam'],
                'option_d' => ['en' => 'Utrecht', 'nl' => 'Utrecht', 'hr' => 'Utrecht', 'se' => 'Utrecht'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the official currency of the Netherlands?', 'nl' => 'Wat is de officiële munteenheid van Nederland?', 'hr' => 'Koja je službena valuta Nizozemske?', 'se' => 'Vad är Nederländernas officiella valuta?'],
                'option_a' => ['en' => 'Euro', 'nl' => 'Euro', 'hr' => 'Euro', 'se' => 'Euro'],
                'option_b' => ['en' => 'Guilder', 'nl' => 'Gulden', 'hr' => 'Gulden', 'se' => 'Gulden'],
                'option_c' => ['en' => 'Dollar', 'nl' => 'Dollar', 'hr' => 'Dolar', 'se' => 'Dollar'],
                'option_d' => ['en' => 'Pound', 'nl' => 'Pond', 'hr' => 'Funta', 'se' => 'Pund'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which flower is the Netherlands most famous for worldwide?', 'nl' => 'Welke bloem is Nederland wereldwijd het meest bekend voor?', 'hr' => 'Po kojem je cvijetu Nizozemska najpoznatija u svijetu?', 'se' => 'Vilken blomma är Nederländerna mest känt för i världen?'],
                'option_a' => ['en' => 'Tulip', 'nl' => 'Tulp', 'hr' => 'Tulipan', 'se' => 'Tulpan'],
                'option_b' => ['en' => 'Rose', 'nl' => 'Roos', 'hr' => 'Ruža', 'se' => 'Ros'],
                'option_c' => ['en' => 'Sunflower', 'nl' => 'Zonnebloem', 'hr' => 'Suncokret', 'se' => 'Solros'],
                'option_d' => ['en' => 'Lily', 'nl' => 'Lelie', 'hr' => 'Ljiljan', 'se' => 'Lilja'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'What was Amsterdam historically famous for cutting?', 'nl' => 'Waar was Amsterdam historisch beroemd voor het slijpen van?', 'hr' => 'Po čemu je Amsterdam povijesno bio poznat u brušenju?', 'se' => 'Vad var Amsterdam historiskt känt för att slipa?'],
                'option_a' => ['en' => 'Diamonds', 'nl' => 'Diamanten', 'hr' => 'Dijamanti', 'se' => 'Diamanter'],
                'option_b' => ['en' => 'Gold', 'nl' => 'Goud', 'hr' => 'Zlato', 'se' => 'Guld'],
                'option_c' => ['en' => 'Silver', 'nl' => 'Zilver', 'hr' => 'Srebro', 'se' => 'Silver'],
                'option_d' => ['en' => 'Glass', 'nl' => 'Glas', 'hr' => 'Staklo', 'se' => 'Glas'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which traditional structure was used to pump water away?', 'nl' => 'Welk traditioneel bouwwerk werd gebruikt om water weg te pompen?', 'hr' => 'Koja je tradicionalna građevina korištena za ispumpavanje vode?', 'se' => 'Vilken traditionell konstruktion användes för att pumpa bort vatten?'],
                'option_a' => ['en' => 'Windmill', 'nl' => 'Molen', 'hr' => 'Vjetrenjača', 'se' => 'Väderkvarn'],
                'option_b' => ['en' => 'Castle', 'nl' => 'Kasteel', 'hr' => 'Dvorac', 'se' => 'Slott'],
                'option_c' => ['en' => 'Tower', 'nl' => 'Toren', 'hr' => 'Toranj', 'se' => 'Torn'],
                'option_d' => ['en' => 'Dike', 'nl' => 'Dijk', 'hr' => 'Nasip', 'se' => 'Vall'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which cheese variety is known worldwide as Dutch?', 'nl' => 'Welke kaassoort is wereldwijd bekend als Nederlands?', 'hr' => 'Koja je vrsta sira diljem svijeta poznata kao nizozemska?', 'se' => 'Vilken ostsort är världskänd som nederländsk?'],
                'option_a' => ['en' => 'Gouda', 'nl' => 'Goudse kaas', 'hr' => 'Gouda', 'se' => 'Gouda'],
                'option_b' => ['en' => 'Brie', 'nl' => 'Brie', 'hr' => 'Brie', 'se' => 'Brie'],
                'option_c' => ['en' => 'Cheddar', 'nl' => 'Cheddar', 'hr' => 'Cheddar', 'se' => 'Cheddar'],
                'option_d' => ['en' => 'Parmesan', 'nl' => 'Parmezaan', 'hr' => 'Parmezan', 'se' => 'Parmesan'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Dutch painter made "The Night Watch"?', 'nl' => 'Welke Nederlandse schilder maakte "De Nachtwacht"?', 'hr' => 'Koji je nizozemski slikar naslikao "Noćnu stražu"?', 'se' => 'Vilken nederländsk konstnär målade "Nattvakten"?'],
                'option_a' => ['en' => 'Rembrandt van Rijn', 'nl' => 'Rembrandt van Rijn', 'hr' => 'Rembrandt van Rijn', 'se' => 'Rembrandt van Rijn'],
                'option_b' => ['en' => 'Vincent van Gogh', 'nl' => 'Vincent van Gogh', 'hr' => 'Vincent van Gogh', 'se' => 'Vincent van Gogh'],
                'option_c' => ['en' => 'Johannes Vermeer', 'nl' => 'Johannes Vermeer', 'hr' => 'Johannes Vermeer', 'se' => 'Johannes Vermeer'],
                'option_d' => ['en' => 'Piet Mondriaan', 'nl' => 'Piet Mondriaan', 'hr' => 'Piet Mondriaan', 'se' => 'Piet Mondriaan'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which city is the International Court of Justice located?', 'nl' => 'In welke stad zit het Internationaal Gerechtshof?', 'hr' => 'U kojem se gradu nalazi Međunarodni sud pravde?', 'se' => 'I vilken stad ligger Internationella domstolen?'],
                'option_a' => ['en' => 'The Hague', 'nl' => 'Den Haag', 'hr' => 'Haag', 'se' => 'Haag'],
                'option_b' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam', 'hr' => 'Amsterdam', 'se' => 'Amsterdam'],
                'option_c' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam', 'hr' => 'Rotterdam', 'se' => 'Rotterdam'],
                'option_d' => ['en' => 'Utrecht', 'nl' => 'Utrecht', 'hr' => 'Utrecht', 'se' => 'Utrecht'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Dutch island does not belong to the Wadden Islands?', 'nl' => 'Welk Nederlands eiland behoort niet tot de Waddeneilanden?', 'hr' => 'Koji nizozemski otok ne pripada Vadenskim otocima?', 'se' => 'Vilken nederländsk ö tillhör inte Vaddöarna?'],
                'option_a' => ['en' => 'Texel', 'nl' => 'Texel', 'hr' => 'Texel', 'se' => 'Texel'],
                'option_b' => ['en' => 'Terschelling', 'nl' => 'Terschelling', 'hr' => 'Terschelling', 'se' => 'Terschelling'],
                'option_c' => ['en' => 'Ameland', 'nl' => 'Ameland', 'hr' => 'Ameland', 'se' => 'Ameland'],
                'option_d' => ['en' => 'Walcheren', 'nl' => 'Walcheren', 'hr' => 'Walcheren', 'se' => 'Walcheren'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the traditional Dutch wooden shoe called?', 'nl' => 'Wat is de traditionele Nederlandse houten schoen genaamd?', 'hr' => 'Kako se zove tradicionalna nizozemska drvena cipela?', 'se' => 'Vad kallas den traditionella nederländska träskon?'],
                'option_a' => ['en' => 'Klomp', 'nl' => 'Klomp', 'hr' => 'Klomp', 'se' => 'Träsko'],
                'option_b' => ['en' => 'Beanie', 'nl' => 'Muts', 'hr' => 'Kapa', 'se' => 'Mössa'],
                'option_c' => ['en' => 'Scarf', 'nl' => 'Sjaal', 'hr' => 'Šal', 'se' => 'Halsduk'],
                'option_d' => ['en' => 'Cap', 'nl' => 'Pet', 'hr' => 'Šilterica', 'se' => 'Keps'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which Dutch city is the famous Van Gogh Museum located?', 'nl' => 'In welke Nederlandse stad staat het beroemde Van Gogh Museum?', 'hr' => 'U kojem se nizozemskom gradu nalazi poznati Van Goghov muzej?', 'se' => 'I vilken nederländsk stad ligger det berömda Van Gogh-museet?'],
                'option_a' => ['en' => 'Amsterdam', 'nl' => 'Amsterdam', 'hr' => 'Amsterdam', 'se' => 'Amsterdam'],
                'option_b' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam', 'hr' => 'Rotterdam', 'se' => 'Rotterdam'],
                'option_c' => ['en' => 'Utrecht', 'nl' => 'Utrecht', 'hr' => 'Utrecht', 'se' => 'Utrecht'],
                'option_d' => ['en' => 'Eindhoven', 'nl' => 'Eindhoven', 'hr' => 'Eindhoven', 'se' => 'Eindhoven'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the best-known Dutch beer producer?', 'nl' => 'Wat is de bekendste Nederlandse bierproducent?', 'hr' => 'Koji je najpoznatiji nizozemski proizvođač piva?', 'se' => 'Vilken är den mest kända nederländska ölproducenten?'],
                'option_a' => ['en' => 'Heineken', 'nl' => 'Heineken', 'hr' => 'Heineken', 'se' => 'Heineken'],
                'option_b' => ['en' => 'Grolsch', 'nl' => 'Grolsch', 'hr' => 'Grolsch', 'se' => 'Grolsch'],
                'option_c' => ['en' => 'Amstel', 'nl' => 'Amstel', 'hr' => 'Amstel', 'se' => 'Amstel'],
                'option_d' => ['en' => 'Bavaria', 'nl' => 'Bavaria', 'hr' => 'Bavaria', 'se' => 'Bavaria'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which sea borders the Netherlands to the north and west?', 'nl' => 'Welke zee grenst aan Nederland in het noorden en westen?', 'hr' => 'Koje more graniči s Nizozemskom na sjeveru i zapadu?', 'se' => 'Vilket hav gränsar till Nederländerna i norr och väster?'],
                'option_a' => ['en' => 'North Sea', 'nl' => 'Noordzee', 'hr' => 'Sjeverno more', 'se' => 'Nordsjön'],
                'option_b' => ['en' => 'Baltic Sea', 'nl' => 'Oostzee', 'hr' => 'Baltičko more', 'se' => 'Östersjön'],
                'option_c' => ['en' => 'Mediterranean Sea', 'nl' => 'Middellandse Zee', 'hr' => 'Sredozemno more', 'se' => 'Medelhavet'],
                'option_d' => ['en' => 'Irish Sea', 'nl' => 'Ierse Zee', 'hr' => 'Irsko more', 'se' => 'Irländska sjön'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the Dutch word for "cheers" when toasting?', 'nl' => 'Wat is het Nederlandse woord voor "cheers" bij het proosten?', 'hr' => 'Koja je nizozemska riječ za "živjeli" pri nazdravljanju?', 'se' => 'Vad är det nederländska ordet för "skål" när man skålar?'],
                'option_a' => ['en' => 'Proost', 'nl' => 'Proost', 'hr' => 'Proost', 'se' => 'Proost'],
                'option_b' => ['en' => 'Skål', 'nl' => 'Skål', 'hr' => 'Skål', 'se' => 'Skål'],
                'option_c' => ['en' => 'Cin cin', 'nl' => 'Cin cin', 'hr' => 'Cin cin', 'se' => 'Cin cin'],
                'option_d' => ['en' => 'Salud', 'nl' => 'Salud', 'hr' => 'Salud', 'se' => 'Salud'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the highest point on the Dutch mainland?', 'nl' => 'Wat is het hoogste punt van het Nederlandse vasteland?', 'hr' => 'Koja je najviša točka nizozemskog kopna?', 'se' => 'Vilken är den högsta punkten på det nederländska fastlandet?'],
                'option_a' => ['en' => 'Vaalserberg', 'nl' => 'Vaalserberg', 'hr' => 'Vaalserberg', 'se' => 'Vaalserberg'],
                'option_b' => ['en' => 'Mont Blanc', 'nl' => 'Mont Blanc', 'hr' => 'Mont Blanc', 'se' => 'Mont Blanc'],
                'option_c' => ['en' => 'Zugspitze', 'nl' => 'Zugspitze', 'hr' => 'Zugspitze', 'se' => 'Zugspitze'],
                'option_d' => ['en' => 'Ben Nevis', 'nl' => 'Ben Nevis', 'hr' => 'Ben Nevis', 'se' => 'Ben Nevis'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'In which year did the Netherlands gain independence from Spain (Peace of Münster)?', 'nl' => 'In welk jaar werd Nederland onafhankelijk van Spanje (Vrede van Münster)?', 'hr' => 'Koje je godine Nizozemska stekla neovisnost od Španjolske (Münsterski mir)?', 'se' => 'Vilket år blev Nederländerna självständigt från Spanien (Freden i Münster)?'],
                'option_a' => ['en' => '1568', 'nl' => '1568', 'hr' => '1568', 'se' => '1568'],
                'option_b' => ['en' => '1648', 'nl' => '1648', 'hr' => '1648', 'se' => '1648'],
                'option_c' => ['en' => '1815', 'nl' => '1815', 'hr' => '1815', 'se' => '1815'],
                'option_d' => ['en' => '1830', 'nl' => '1830', 'hr' => '1830', 'se' => '1830'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which famous Dutch event involves skating long distances along frozen canals past eleven cities?', 'nl' => 'Welk beroemd Nederlands evenement bestaat uit schaatsen langs elf steden over bevroren kanalen?', 'hr' => 'Koji poznati nizozemski događaj uključuje klizanje na velike udaljenosti zaleđenim kanalima kroz jedanaest gradova?', 'se' => 'Vilket berömt nederländskt evenemang innebär skridskoåkning långa sträckor längs frusna kanaler förbi elva städer?'],
                'option_a' => ['en' => 'Elfstedentocht', 'nl' => 'Elfstedentocht', 'hr' => 'Elfstedentocht', 'se' => 'Elfstedentocht'],
                'option_b' => ['en' => 'Formula 1', 'nl' => 'Formule 1', 'hr' => 'Formula 1', 'se' => 'Formel 1'],
                'option_c' => ['en' => 'Cricket', 'nl' => 'Cricket', 'hr' => 'Kriket', 'se' => 'Cricket'],
                'option_d' => ['en' => 'Rugby', 'nl' => 'Rugby', 'hr' => 'Ragbi', 'se' => 'Rugby'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Dutch province is home to the city of Maastricht?', 'nl' => 'In welke Nederlandse provincie ligt de stad Maastricht?', 'hr' => 'U kojoj se nizozemskoj pokrajini nalazi grad Maastricht?', 'se' => 'I vilken nederländsk provins ligger staden Maastricht?'],
                'option_a' => ['en' => 'Limburg', 'nl' => 'Limburg', 'hr' => 'Limburg', 'se' => 'Limburg'],
                'option_b' => ['en' => 'Groningen', 'nl' => 'Groningen', 'hr' => 'Groningen', 'se' => 'Groningen'],
                'option_c' => ['en' => 'Zeeland', 'nl' => 'Zeeland', 'hr' => 'Zeeland', 'se' => 'Zeeland'],
                'option_d' => ['en' => 'Friesland', 'nl' => 'Friesland', 'hr' => 'Friesland', 'se' => 'Friesland'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'A large part of the Netherlands lies below what?', 'nl' => 'Een groot deel van Nederland ligt onder wat?', 'hr' => 'Velik dio Nizozemske leži ispod čega?', 'se' => 'En stor del av Nederländerna ligger under vad?'],
                'option_a' => ['en' => 'Sea level', 'nl' => 'Zeeniveau', 'hr' => 'Razina mora', 'se' => 'Havsnivå'],
                'option_b' => ['en' => 'Cloud level', 'nl' => 'Wolkenniveau', 'hr' => 'Razina oblaka', 'se' => 'Molnnivå'],
                'option_c' => ['en' => 'Mountain level', 'nl' => 'Bergniveau', 'hr' => 'Razina planina', 'se' => 'Bergsnivå'],
                'option_d' => ['en' => 'Snow level', 'nl' => 'Sneeuwniveau', 'hr' => 'Razina snijega', 'se' => 'Snönivå'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Who led the Dutch Revolt against Spain as the first Prince of Orange?', 'nl' => 'Wie leidde de Nederlandse Opstand tegen Spanje als eerste Prins van Oranje?', 'hr' => 'Tko je predvodio Nizozemski ustanak protiv Španjolske kao prvi princ Oranski?', 'se' => 'Vem ledde det nederländska upproret mot Spanien som den förste prinsen av Oranien?'],
                'option_a' => ['en' => 'William the Silent', 'nl' => 'Willem van Oranje', 'hr' => 'Vilim Šutljivi', 'se' => 'Vilhelm av Oranien'],
                'option_b' => ['en' => 'Maurice of Nassau', 'nl' => 'Maurits van Nassau', 'hr' => 'Mavricije Nasauski', 'se' => 'Moritz av Nassau'],
                'option_c' => ['en' => 'William III', 'nl' => 'Willem III', 'hr' => 'Vilim III', 'se' => 'Vilhelm III'],
                'option_d' => ['en' => 'Johan de Witt', 'nl' => 'Johan de Witt', 'hr' => 'Johan de Witt', 'se' => 'Johan de Witt'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Dutch artist pioneered the geometric abstraction of the De Stijl movement?', 'nl' => 'Welke Nederlandse kunstenaar was een pionier van de geometrische abstractie van De Stijl?', 'hr' => 'Koji je nizozemski umjetnik bio pionir geometrijske apstrakcije pokreta De Stijl?', 'se' => 'Vilken nederländsk konstnär var pionjär inom den geometriska abstraktionen i De Stijl-rörelsen?'],
                'option_a' => ['en' => 'Piet Mondriaan', 'nl' => 'Piet Mondriaan', 'hr' => 'Piet Mondriaan', 'se' => 'Piet Mondriaan'],
                'option_b' => ['en' => 'Rembrandt van Rijn', 'nl' => 'Rembrandt van Rijn', 'hr' => 'Rembrandt van Rijn', 'se' => 'Rembrandt van Rijn'],
                'option_c' => ['en' => 'Johannes Vermeer', 'nl' => 'Johannes Vermeer', 'hr' => 'Johannes Vermeer', 'se' => 'Johannes Vermeer'],
                'option_d' => ['en' => 'M.C. Escher', 'nl' => 'M.C. Escher', 'hr' => 'M.C. Escher', 'se' => 'M.C. Escher'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the name of the large flood protection system built after the 1953 North Sea flood?', 'nl' => 'Wat is de naam van het grote waterkeringssysteem dat werd gebouwd na de watersnoodramp van 1953?', 'hr' => 'Kako se zove veliki sustav zaštite od poplava izgrađen nakon poplave Sjevernog mora 1953. godine?', 'se' => 'Vad heter det stora översvämningsskyddssystemet som byggdes efter Nordsjöoversvämningen 1953?'],
                'option_a' => ['en' => 'Delta Works', 'nl' => 'Deltawerken', 'hr' => 'Delta projekt', 'se' => 'Deltaverken'],
                'option_b' => ['en' => 'Berlin Wall', 'nl' => 'Berlijnse Muur', 'hr' => 'Berlinski zid', 'se' => 'Berlinmuren'],
                'option_c' => ['en' => 'Hoover Dam', 'nl' => 'Hoover Dam', 'hr' => 'Hooverova brana', 'se' => 'Hooverdammen'],
                'option_d' => ['en' => 'Thames Barrier', 'nl' => 'Thames Barrier', 'hr' => 'Brana na Temzi', 'se' => 'Thamesbarriären'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Dutch holiday features a character who arrives by steamboat every November?', 'nl' => 'Welk Nederlands feest kent een figuur die elk jaar in november per stoomboot aankomt?', 'hr' => 'Koji nizozemski blagdan uključuje lik koji svake godine u studenom stiže parobrodom?', 'se' => 'Vilken nederländsk högtid har en karaktär som anländer med ångbåt varje november?'],
                'option_a' => ['en' => 'Sinterklaas', 'nl' => 'Sinterklaas', 'hr' => 'Sinterklaas', 'se' => 'Sinterklaas'],
                'option_b' => ['en' => 'Halloween', 'nl' => 'Halloween', 'hr' => 'Noć vještica', 'se' => 'Halloween'],
                'option_c' => ['en' => 'Oktoberfest', 'nl' => 'Oktoberfest', 'hr' => 'Oktoberfest', 'se' => 'Oktoberfest'],
                'option_d' => ['en' => 'Carnival', 'nl' => 'Carnaval', 'hr' => 'Karneval', 'se' => 'Karneval'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the second-largest city in the Netherlands by population?', 'nl' => 'Wat is de tweede grootste stad van Nederland qua inwoners?', 'hr' => 'Koji je drugi po veličini grad u Nizozemskoj prema broju stanovnika?', 'se' => 'Vilken är den näst största staden i Nederländerna befolkningsmässigt?'],
                'option_a' => ['en' => 'Rotterdam', 'nl' => 'Rotterdam', 'hr' => 'Rotterdam', 'se' => 'Rotterdam'],
                'option_b' => ['en' => 'Utrecht', 'nl' => 'Utrecht', 'hr' => 'Utrecht', 'se' => 'Utrecht'],
                'option_c' => ['en' => 'The Hague', 'nl' => 'Den Haag', 'hr' => 'Haag', 'se' => 'Haag'],
                'option_d' => ['en' => 'Eindhoven', 'nl' => 'Eindhoven', 'hr' => 'Eindhoven', 'se' => 'Eindhoven'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'NL',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Dutch national park is famous for its Kröller-Müller Museum and free-roaming wildlife?', 'nl' => 'Welk Nederlands nationaal park is beroemd om het Kröller-Müller Museum en vrij rondlopend wild?', 'hr' => 'Koji je nizozemski nacionalni park poznat po muzeju Kröller-Müller i slobodno rasprostranjenoj divljači?', 'se' => 'Vilken nederländsk nationalpark är känd för Kröller-Müller-museet och fritt strövande vilda djur?'],
                'option_a' => ['en' => 'Hoge Veluwe', 'nl' => 'Hoge Veluwe', 'hr' => 'Hoge Veluwe', 'se' => 'Hoge Veluwe'],
                'option_b' => ['en' => 'Biesbosch', 'nl' => 'Biesbosch', 'hr' => 'Biesbosch', 'se' => 'Biesbosch'],
                'option_c' => ['en' => 'Schiermonnikoog', 'nl' => 'Schiermonnikoog', 'hr' => 'Schiermonnikoog', 'se' => 'Schiermonnikoog'],
                'option_d' => ['en' => 'Veluwezoom', 'nl' => 'Veluwezoom', 'hr' => 'Veluwezoom', 'se' => 'Veluwezoom'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which year was the Dutch East India Company (VOC) founded?', 'nl' => 'In welk jaar werd de Verenigde Oost-Indische Compagnie (VOC) opgericht?', 'hr' => 'Koje je godine osnovana Nizozemska istočnoindijska kompanija (VOC)?', 'se' => 'Vilket år grundades Nederländska Ostindiska kompaniet (VOC)?'],
                'option_a' => ['en' => '1602', 'nl' => '1602', 'hr' => '1602', 'se' => '1602'],
                'option_b' => ['en' => '1648', 'nl' => '1648', 'hr' => '1648', 'se' => '1648'],
                'option_c' => ['en' => '1700', 'nl' => '1700', 'hr' => '1700', 'se' => '1700'],
                'option_d' => ['en' => '1795', 'nl' => '1795', 'hr' => '1795', 'se' => '1795'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'NL',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'What is the title of the Dutch national anthem?', 'nl' => 'Wat is de titel van het Nederlandse volkslied?', 'hr' => 'Kako se zove nizozemska himna?', 'se' => 'Vad heter den nederländska nationalsången?'],
                'option_a' => ['en' => 'Wilhelmus', 'nl' => 'Wilhelmus', 'hr' => 'Wilhelmus', 'se' => 'Wilhelmus'],
                'option_b' => ['en' => 'Het Volkslied', 'nl' => 'Het Volkslied', 'hr' => 'Het Volkslied', 'se' => 'Het Volkslied'],
                'option_c' => ['en' => 'Oranje Boven', 'nl' => 'Oranje Boven', 'hr' => 'Oranje Boven', 'se' => 'Oranje Boven'],
                'option_d' => ['en' => 'Marseillaise', 'nl' => 'Marseillaise', 'hr' => 'Marseljeza', 'se' => 'Marseljäsen'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'NL',
                'difficulty' => 'hard',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function swedenQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'What is the capital of Sweden?', 'nl' => 'Wat is de hoofdstad van Zweden?', 'hr' => 'Koji je glavni grad Švedske?', 'se' => 'Vad är Sveriges huvudstad?'],
                'option_a' => ['en' => 'Malmö', 'nl' => 'Malmö', 'hr' => 'Malmö', 'se' => 'Malmö'],
                'option_b' => ['en' => 'Stockholm', 'nl' => 'Stockholm', 'hr' => 'Stockholm', 'se' => 'Stockholm'],
                'option_c' => ['en' => 'Gothenburg', 'nl' => 'Göteborg', 'hr' => 'Göteborg', 'se' => 'Göteborg'],
                'option_d' => ['en' => 'Uppsala', 'nl' => 'Uppsala', 'hr' => 'Uppsala', 'se' => 'Uppsala'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which country shares a land border with Sweden?', 'nl' => 'Welk land deelt een landgrens met Zweden?', 'hr' => 'Koja država dijeli kopnenu granicu sa Švedskom?', 'se' => 'Vilket land delar landgräns med Sverige?'],
                'option_a' => ['en' => 'Norway', 'nl' => 'Noorwegen', 'hr' => 'Norveška', 'se' => 'Norge'],
                'option_b' => ['en' => 'Denmark', 'nl' => 'Denemarken', 'hr' => 'Danska', 'se' => 'Danmark'],
                'option_c' => ['en' => 'Germany', 'nl' => 'Duitsland', 'hr' => 'Njemačka', 'se' => 'Tyskland'],
                'option_d' => ['en' => 'Poland', 'nl' => 'Polen', 'hr' => 'Poljska', 'se' => 'Polen'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is a traditional Swedish food?', 'nl' => 'Welke van deze is een traditioneel Zweeds gerecht?', 'hr' => 'Koje je od ovoga tradicionalno švedsko jelo?', 'se' => 'Vilken av dessa är en traditionell svensk maträtt?'],
                'option_a' => ['en' => 'Paella', 'nl' => 'Paella', 'hr' => 'Paella', 'se' => 'Paella'],
                'option_b' => ['en' => 'Köttbullar', 'nl' => 'Köttbullar', 'hr' => 'Köttbullar', 'se' => 'Köttbullar'],
                'option_c' => ['en' => 'Sushi', 'nl' => 'Sushi', 'hr' => 'Sushi', 'se' => 'Sushi'],
                'option_d' => ['en' => 'Tacos', 'nl' => 'Tacos', 'hr' => 'Tacos', 'se' => 'Tacos'],
                'correct_option' => 'B',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What color is the cross on the Swedish flag?', 'nl' => 'Welke kleur heeft het kruis op de Zweedse vlag?', 'hr' => 'Koje je boje križ na švedskoj zastavi?', 'se' => 'Vilken färg har korset på den svenska flaggan?'],
                'option_a' => ['en' => 'Yellow', 'nl' => 'Geel', 'hr' => 'Žuta', 'se' => 'Gul'],
                'option_b' => ['en' => 'Red', 'nl' => 'Rood', 'hr' => 'Crvena', 'se' => 'Röd'],
                'option_c' => ['en' => 'White', 'nl' => 'Wit', 'hr' => 'Bijela', 'se' => 'Vit'],
                'option_d' => ['en' => 'Black', 'nl' => 'Zwart', 'hr' => 'Crna', 'se' => 'Svart'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is "fika" in Sweden?', 'nl' => 'Wat is "fika" in Zweden?', 'hr' => 'Što je "fika" u Švedskoj?', 'se' => 'Vad är "fika" i Sverige?'],
                'option_a' => ['en' => 'A coffee break', 'nl' => 'Een koffiepauze', 'hr' => 'Pauza za kavu', 'se' => 'Ett kaffeavbrott'],
                'option_b' => ['en' => 'A national holiday', 'nl' => 'Een nationale feestdag', 'hr' => 'Državni praznik', 'se' => 'En nationell helgdag'],
                'option_c' => ['en' => 'A type of dance', 'nl' => 'Een soort dans', 'hr' => 'Vrsta plesa', 'se' => 'En typ av dans'],
                'option_d' => ['en' => 'A winter sport', 'nl' => 'Een wintersport', 'hr' => 'Zimski sport', 'se' => 'En vintersport'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "Which of these is Sweden's largest island?", 'nl' => 'Wat is het grootste eiland van Zweden?', 'hr' => 'Koji je najveći švedski otok?', 'se' => 'Vilken är Sveriges största ö?'],
                'option_a' => ['en' => 'Gotland', 'nl' => 'Gotland', 'hr' => 'Gotland', 'se' => 'Gotland'],
                'option_b' => ['en' => 'Öland', 'nl' => 'Öland', 'hr' => 'Öland', 'se' => 'Öland'],
                'option_c' => ['en' => 'Bornholm', 'nl' => 'Bornholm', 'hr' => 'Bornholm', 'se' => 'Bornholm'],
                'option_d' => ['en' => 'Åland', 'nl' => 'Åland', 'hr' => 'Åland', 'se' => 'Åland'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which city is connected to Copenhagen by the Öresund Bridge?', 'nl' => 'Welke stad is via de Öresundbrug verbonden met Kopenhagen?', 'hr' => 'Koji je grad povezan s Kopenhagenom Öresundskim mostom?', 'se' => 'Vilken stad är förbunden med Köpenhamn via Öresundsbron?'],
                'option_a' => ['en' => 'Stockholm', 'nl' => 'Stockholm', 'hr' => 'Stockholm', 'se' => 'Stockholm'],
                'option_b' => ['en' => 'Malmö', 'nl' => 'Malmö', 'hr' => 'Malmö', 'se' => 'Malmö'],
                'option_c' => ['en' => 'Gothenburg', 'nl' => 'Göteborg', 'hr' => 'Göteborg', 'se' => 'Göteborg'],
                'option_d' => ['en' => 'Lund', 'nl' => 'Lund', 'hr' => 'Lund', 'se' => 'Lund'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these people is NOT Swedish?', 'nl' => 'Wie van deze personen is NIET Zweeds?', 'hr' => 'Koja od ovih osoba NIJE Šveđanin?', 'se' => 'Vilken av dessa personer är INTE svensk?'],
                'option_a' => ['en' => 'Alfred Nobel', 'nl' => 'Alfred Nobel', 'hr' => 'Alfred Nobel', 'se' => 'Alfred Nobel'],
                'option_b' => ['en' => 'Anders Celsius', 'nl' => 'Anders Celsius', 'hr' => 'Anders Celsius', 'se' => 'Anders Celsius'],
                'option_c' => ['en' => 'Carl Linnaeus', 'nl' => 'Carl Linnaeus', 'hr' => 'Carl Linnaeus', 'se' => 'Carl von Linné'],
                'option_d' => ['en' => 'Isaac Newton', 'nl' => 'Isaac Newton', 'hr' => 'Isaac Newton', 'se' => 'Isaac Newton'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which political party leads Sweden's government?", 'nl' => 'Welke politieke partij leidt de Zweedse regering?', 'hr' => 'Koja politička stranka predvodi vladu Švedske?', 'se' => 'Vilket politiskt parti leder Sveriges regering?'],
                'option_a' => ['en' => 'Moderaterna', 'nl' => 'Moderaterna', 'hr' => 'Moderaterna', 'se' => 'Moderaterna'],
                'option_b' => ['en' => 'Socialdemokraterna', 'nl' => 'Socialdemokraterna', 'hr' => 'Socialdemokraterna', 'se' => 'Socialdemokraterna'],
                'option_c' => ['en' => 'Sverigedemokraterna', 'nl' => 'Sverigedemokraterna', 'hr' => 'Sverigedemokraterna', 'se' => 'Sverigedemokraterna'],
                'option_d' => ['en' => 'Liberalerna', 'nl' => 'Liberalerna', 'hr' => 'Liberalerna', 'se' => 'Liberalerna'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which of these is NOT a common feature of Sweden's landscape?", 'nl' => 'Wat is GEEN veelvoorkomend kenmerk van het Zweedse landschap?', 'hr' => 'Što NIJE uobičajena značajka švedskog krajolika?', 'se' => 'Vad är INTE ett vanligt inslag i det svenska landskapet?'],
                'option_a' => ['en' => 'Forests', 'nl' => 'Bossen', 'hr' => 'Šume', 'se' => 'Skogar'],
                'option_b' => ['en' => 'Lakes', 'nl' => 'Meren', 'hr' => 'Jezera', 'se' => 'Sjöar'],
                'option_c' => ['en' => 'Mountains', 'nl' => 'Bergen', 'hr' => 'Planine', 'se' => 'Berg'],
                'option_d' => ['en' => 'Deserts', 'nl' => 'Woestijnen', 'hr' => 'Pustinje', 'se' => 'Öknar'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Swedish king was killed at the Battle of Lützen in 1632?', 'nl' => 'Welke Zweedse koning sneuvelde in de Slag bij Lützen in 1632?', 'hr' => 'Koji je švedski kralj poginuo u bitci kod Lützena 1632. godine?', 'se' => 'Vilken svensk kung dödades i slaget vid Lützen 1632?'],
                'option_a' => ['en' => 'Charles XII', 'nl' => 'Karel XII', 'hr' => 'Karlo XII', 'se' => 'Karl XII'],
                'option_b' => ['en' => 'Gustav II Adolf', 'nl' => 'Gustav II Adolf', 'hr' => 'Gustav II Adolf', 'se' => 'Gustav II Adolf'],
                'option_c' => ['en' => 'Gustav Vasa', 'nl' => 'Gustav Vasa', 'hr' => 'Gustav Vasa', 'se' => 'Gustav Vasa'],
                'option_d' => ['en' => 'Oscar II', 'nl' => 'Oscar II', 'hr' => 'Oscar II', 'se' => 'Oscar II'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these was NOT ceded to Sweden under the Treaty of Roskilde (1658)?', 'nl' => 'Wat werd NIET aan Zweden afgestaan onder het Verdrag van Roskilde (1658)?', 'hr' => 'Što NIJE ustupljeno Švedskoj Roskildskim mirom (1658.)?', 'se' => 'Vad avträddes INTE till Sverige genom freden i Roskilde (1658)?'],
                'option_a' => ['en' => 'Scania', 'nl' => 'Schonen', 'hr' => 'Skåne', 'se' => 'Skåne'],
                'option_b' => ['en' => 'Blekinge', 'nl' => 'Blekinge', 'hr' => 'Blekinge', 'se' => 'Blekinge'],
                'option_c' => ['en' => 'Bohuslän', 'nl' => 'Bohuslän', 'hr' => 'Bohuslän', 'se' => 'Bohuslän'],
                'option_d' => ['en' => 'Gotland', 'nl' => 'Gotland', 'hr' => 'Gotland', 'se' => 'Gotland'],
                'correct_option' => 'D',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => "What is Sweden's highest mountain?", 'nl' => 'Wat is de hoogste berg van Zweden?', 'hr' => 'Koja je najviša planina Švedske?', 'se' => 'Vilket är Sveriges högsta berg?'],
                'option_a' => ['en' => 'Kebnekaise', 'nl' => 'Kebnekaise', 'hr' => 'Kebnekaise', 'se' => 'Kebnekaise'],
                'option_b' => ['en' => 'Helags', 'nl' => 'Helags', 'hr' => 'Helags', 'se' => 'Helags'],
                'option_c' => ['en' => 'Åreskutan', 'nl' => 'Åreskutan', 'hr' => 'Åreskutan', 'se' => 'Åreskutan'],
                'option_d' => ['en' => 'Sarektjåkkå', 'nl' => 'Sarektjåkkå', 'hr' => 'Sarektjåkkå', 'se' => 'Sarektjåkkå'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT a Swedish lake?', 'nl' => 'Welk van deze is GEEN Zweeds meer?', 'hr' => 'Koje od ovih NIJE švedsko jezero?', 'se' => 'Vilken av dessa är INTE en svensk sjö?'],
                'option_a' => ['en' => 'Vänern', 'nl' => 'Vänern', 'hr' => 'Vänern', 'se' => 'Vänern'],
                'option_b' => ['en' => 'Vättern', 'nl' => 'Vättern', 'hr' => 'Vättern', 'se' => 'Vättern'],
                'option_c' => ['en' => 'Mälaren', 'nl' => 'Mälaren', 'hr' => 'Mälaren', 'se' => 'Mälaren'],
                'option_d' => ['en' => 'Lake Geneva', 'nl' => 'Meer van Genève', 'hr' => 'Ženevsko jezero', 'se' => 'Genèvesjön'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which year did the warship Vasa sink?', 'nl' => 'In welk jaar zonk het oorlogsschip Vasa?', 'hr' => 'Koje je godine potonuo ratni brod Vasa?', 'se' => 'Vilket år sjönk krigsskeppet Vasa?'],
                'option_a' => ['en' => '1523', 'nl' => '1523', 'hr' => '1523', 'se' => '1523'],
                'option_b' => ['en' => '1628', 'nl' => '1628', 'hr' => '1628', 'se' => '1628'],
                'option_c' => ['en' => '1709', 'nl' => '1709', 'hr' => '1709', 'se' => '1709'],
                'option_d' => ['en' => '1814', 'nl' => '1814', 'hr' => '1814', 'se' => '1814'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the second-largest city in Sweden?', 'nl' => 'Wat is de tweede grootste stad van Zweden?', 'hr' => 'Koji je drugi po veličini grad Švedske?', 'se' => 'Vilken är Sveriges näst största stad?'],
                'option_a' => ['en' => 'Malmö', 'nl' => 'Malmö', 'hr' => 'Malmö', 'se' => 'Malmö'],
                'option_b' => ['en' => 'Gothenburg', 'nl' => 'Göteborg', 'hr' => 'Göteborg', 'se' => 'Göteborg'],
                'option_c' => ['en' => 'Uppsala', 'nl' => 'Uppsala', 'hr' => 'Uppsala', 'se' => 'Uppsala'],
                'option_d' => ['en' => 'Örebro', 'nl' => 'Örebro', 'hr' => 'Örebro', 'se' => 'Örebro'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which furniture retailer is a famous Swedish brand known worldwide?', 'nl' => 'Welke meubelketen is een wereldberoemd Zweeds merk?', 'hr' => 'Koji je trgovac namještajem poznat švedski brend diljem svijeta?', 'se' => 'Vilken möbelkedja är ett känt svenskt varumärke över hela världen?'],
                'option_a' => ['en' => 'IKEA', 'nl' => 'IKEA', 'hr' => 'IKEA', 'se' => 'IKEA'],
                'option_b' => ['en' => 'Walmart', 'nl' => 'Walmart', 'hr' => 'Walmart', 'se' => 'Walmart'],
                'option_c' => ['en' => 'Target', 'nl' => 'Target', 'hr' => 'Target', 'se' => 'Target'],
                'option_d' => ['en' => 'Argos', 'nl' => 'Argos', 'hr' => 'Argos', 'se' => 'Argos'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "Which animal is considered a symbol of Sweden's forests?", 'nl' => 'Welk dier wordt beschouwd als symbool van de Zweedse bossen?', 'hr' => 'Koja se životinja smatra simbolom švedskih šuma?', 'se' => 'Vilket djur anses vara en symbol för Sveriges skogar?'],
                'option_a' => ['en' => 'Moose (elk)', 'nl' => 'Eland', 'hr' => 'Los', 'se' => 'Älg'],
                'option_b' => ['en' => 'Lion', 'nl' => 'Leeuw', 'hr' => 'Lav', 'se' => 'Lejon'],
                'option_c' => ['en' => 'Eagle', 'nl' => 'Adelaar', 'hr' => 'Orao', 'se' => 'Örn'],
                'option_d' => ['en' => 'Bear', 'nl' => 'Beer', 'hr' => 'Medvjed', 'se' => 'Björn'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Swedish pop group won Eurovision in 1974 with "Waterloo"?', 'nl' => 'Welke Zweedse popgroep won het Eurovisiesongfestival in 1974 met "Waterloo"?', 'hr' => 'Koja je švedska pop grupa pobijedila na Euroviziji 1974. s pjesmom "Waterloo"?', 'se' => 'Vilken svensk popgrupp vann Eurovision 1974 med "Waterloo"?'],
                'option_a' => ['en' => 'ABBA', 'nl' => 'ABBA', 'hr' => 'ABBA', 'se' => 'ABBA'],
                'option_b' => ['en' => 'Roxette', 'nl' => 'Roxette', 'hr' => 'Roxette', 'se' => 'Roxette'],
                'option_c' => ['en' => 'Ace of Base', 'nl' => 'Ace of Base', 'hr' => 'Ace of Base', 'se' => 'Ace of Base'],
                'option_d' => ['en' => 'Europe', 'nl' => 'Europe', 'hr' => 'Europe', 'se' => 'Europe'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "What is the name of Sweden's Arctic region, known for the midnight sun?", 'nl' => 'Hoe heet de Zweedse Arctische regio die bekendstaat om de middernachtzon?', 'hr' => 'Kako se zove švedska arktička regija poznata po ponoćnom suncu?', 'se' => 'Vad heter Sveriges arktiska region, känd för midnattssolen?'],
                'option_a' => ['en' => 'Lapland', 'nl' => 'Lapland', 'hr' => 'Laponija', 'se' => 'Lappland'],
                'option_b' => ['en' => 'Provence', 'nl' => 'Provence', 'hr' => 'Provansa', 'se' => 'Provence'],
                'option_c' => ['en' => 'Bavaria', 'nl' => 'Beieren', 'hr' => 'Bavarska', 'se' => 'Bayern'],
                'option_d' => ['en' => 'Tuscany', 'nl' => 'Toscane', 'hr' => 'Toskana', 'se' => 'Toscana'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Swedish nobleman traditionally founded Stockholm in 1252?', 'nl' => 'Welke Zweedse edelman stichtte traditioneel Stockholm in 1252?', 'hr' => 'Koji je švedski plemić prema tradiciji osnovao Stockholm 1252. godine?', 'se' => 'Vilken svensk adelsman grundade enligt traditionen Stockholm 1252?'],
                'option_a' => ['en' => 'Birger Jarl', 'nl' => 'Birger Jarl', 'hr' => 'Birger Jarl', 'se' => 'Birger Jarl'],
                'option_b' => ['en' => 'Gustav Vasa', 'nl' => 'Gustav Vasa', 'hr' => 'Gustav Vasa', 'se' => 'Gustav Vasa'],
                'option_c' => ['en' => 'Charles XII', 'nl' => 'Karel XII', 'hr' => 'Karlo XII', 'se' => 'Karl XII'],
                'option_d' => ['en' => 'Carl XVI Gustaf', 'nl' => 'Carl XVI Gustaf', 'hr' => 'Carl XVI Gustaf', 'se' => 'Carl XVI Gustaf'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "What is the largest land carnivore living in Sweden's wild?", 'nl' => 'Wat is het grootste landroofdier dat in het wild in Zweden leeft?', 'hr' => 'Koji je najveći kopneni mesožder koji živi u divljini Švedske?', 'se' => 'Vilket är det största landlevande rovdjuret i Sveriges vildmark?'],
                'option_a' => ['en' => 'Brown bear', 'nl' => 'Bruine beer', 'hr' => 'Smeđi medvjed', 'se' => 'Brunbjörn'],
                'option_b' => ['en' => 'Tiger', 'nl' => 'Tijger', 'hr' => 'Tigar', 'se' => 'Tiger'],
                'option_c' => ['en' => 'Lion', 'nl' => 'Leeuw', 'hr' => 'Lav', 'se' => 'Lejon'],
                'option_d' => ['en' => 'Jaguar', 'nl' => 'Jaguar', 'hr' => 'Jaguar', 'se' => 'Jaguar'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which 1709 battle did Sweden suffer a decisive defeat to Russia under Peter the Great?', 'nl' => 'In welke veldslag van 1709 leed Zweden een beslissende nederlaag tegen Rusland onder Peter de Grote?', 'hr' => 'U kojoj je bitci 1709. godine Švedska doživjela odlučujući poraz od Rusije pod Petrom Velikim?', 'se' => 'I vilket slag 1709 led Sverige ett avgörande nederlag mot Ryssland under Peter den store?'],
                'option_a' => ['en' => 'Battle of Poltava', 'nl' => 'Slag bij Poltava', 'hr' => 'Bitka kod Poltave', 'se' => 'Slaget vid Poltava'],
                'option_b' => ['en' => 'Battle of Narva', 'nl' => 'Slag bij Narva', 'hr' => 'Bitka kod Narve', 'se' => 'Slaget vid Narva'],
                'option_c' => ['en' => 'Battle of Lützen', 'nl' => 'Slag bij Lützen', 'hr' => 'Bitka kod Lützena', 'se' => 'Slaget vid Lützen'],
                'option_d' => ['en' => 'Battle of Waterloo', 'nl' => 'Slag bij Waterloo', 'hr' => 'Bitka kod Waterlooa', 'se' => 'Slaget vid Waterloo'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Swedish author created the character Pippi Longstocking?', 'nl' => 'Welke Zweedse schrijver bedacht het personage Pippi Langkous?', 'hr' => 'Koja je švedska autorica stvorila lik Pipi Duge Čarape?', 'se' => 'Vilken svensk författare skapade karaktären Pippi Långstrump?'],
                'option_a' => ['en' => 'Astrid Lindgren', 'nl' => 'Astrid Lindgren', 'hr' => 'Astrid Lindgren', 'se' => 'Astrid Lindgren'],
                'option_b' => ['en' => 'Stieg Larsson', 'nl' => 'Stieg Larsson', 'hr' => 'Stieg Larsson', 'se' => 'Stieg Larsson'],
                'option_c' => ['en' => 'Henning Mankell', 'nl' => 'Henning Mankell', 'hr' => 'Henning Mankell', 'se' => 'Henning Mankell'],
                'option_d' => ['en' => 'Selma Lagerlöf', 'nl' => 'Selma Lagerlöf', 'hr' => 'Selma Lagerlöf', 'se' => 'Selma Lagerlöf'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What is the name of the strait separating southern Sweden from Denmark?', 'nl' => 'Hoe heet de zeestraat die het zuiden van Zweden scheidt van Denemarken?', 'hr' => 'Kako se zove tjesnac koji odvaja južnu Švedsku od Danske?', 'se' => 'Vad heter sundet som skiljer södra Sverige från Danmark?'],
                'option_a' => ['en' => 'Öresund', 'nl' => 'Öresund', 'hr' => 'Öresund', 'se' => 'Öresund'],
                'option_b' => ['en' => 'Bosphorus', 'nl' => 'Bosporus', 'hr' => 'Bosfor', 'se' => 'Bosporen'],
                'option_c' => ['en' => 'Strait of Gibraltar', 'nl' => 'Straat van Gibraltar', 'hr' => 'Gibraltarski tjesnac', 'se' => 'Gibraltarsund'],
                'option_d' => ['en' => 'English Channel', 'nl' => 'Het Kanaal', 'hr' => 'Engleski kanal', 'se' => 'Engelska kanalen'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which Swedish city is the Nobel Prize awarded each year (except the Peace Prize)?', 'nl' => 'In welke Zweedse stad wordt de Nobelprijs elk jaar uitgereikt (behalve de Vredesprijs)?', 'hr' => 'U kojem se švedskom gradu svake godine dodjeljuje Nobelova nagrada (osim Nagrade za mir)?', 'se' => 'I vilken svensk stad delas Nobelpriset ut varje år (utom Fredspriset)?'],
                'option_a' => ['en' => 'Stockholm', 'nl' => 'Stockholm', 'hr' => 'Stockholm', 'se' => 'Stockholm'],
                'option_b' => ['en' => 'Gothenburg', 'nl' => 'Göteborg', 'hr' => 'Göteborg', 'se' => 'Göteborg'],
                'option_c' => ['en' => 'Malmö', 'nl' => 'Malmö', 'hr' => 'Malmö', 'se' => 'Malmö'],
                'option_d' => ['en' => 'Uppsala', 'nl' => 'Uppsala', 'hr' => 'Uppsala', 'se' => 'Uppsala'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is the longest river in Sweden?', 'nl' => 'Wat is de langste rivier van Zweden?', 'hr' => 'Koja je najduža rijeka u Švedskoj?', 'se' => 'Vilken är Sveriges längsta flod?'],
                'option_a' => ['en' => 'Torne River', 'nl' => 'Torne', 'hr' => 'Torne', 'se' => 'Torne älv'],
                'option_b' => ['en' => 'Klarälven', 'nl' => 'Klarälven', 'hr' => 'Klarälven', 'se' => 'Klarälven'],
                'option_c' => ['en' => 'Dalälven', 'nl' => 'Dalälven', 'hr' => 'Dalälven', 'se' => 'Dalälven'],
                'option_d' => ['en' => 'Göta River', 'nl' => 'Göta', 'hr' => 'Göta', 'se' => 'Göta älv'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'In which year did Sweden join the European Union?', 'nl' => 'In welk jaar werd Zweden lid van de Europese Unie?', 'hr' => 'Koje je godine Švedska pristupila Europskoj uniji?', 'se' => 'Vilket år gick Sverige med i Europeiska unionen?'],
                'option_a' => ['en' => '1995', 'nl' => '1995', 'hr' => '1995', 'se' => '1995'],
                'option_b' => ['en' => '1989', 'nl' => '1989', 'hr' => '1989', 'se' => '1989'],
                'option_c' => ['en' => '2000', 'nl' => '2000', 'hr' => '2000', 'se' => '2000'],
                'option_d' => ['en' => '1973', 'nl' => '1973', 'hr' => '1973', 'se' => '1973'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'SE',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Swedish midsummer tradition involves dancing around a flower-decorated pole?', 'nl' => 'Welke Zweedse midzomertraditie draait om dansen rond een met bloemen versierde paal?', 'hr' => 'Koja švedska tradicija ivanjske noći uključuje ples oko stupa ukrašenog cvijećem?', 'se' => 'Vilken svensk midsommartradition innebär dans runt en blomsterklädd stång?'],
                'option_a' => ['en' => 'Maypole dancing', 'nl' => 'Meiboomdansen', 'hr' => 'Ples oko stupa', 'se' => 'Dans kring midsommarstången'],
                'option_b' => ['en' => 'Fire jumping', 'nl' => 'Over het vuur springen', 'hr' => 'Preskakanje vatre', 'se' => 'Eldhoppning'],
                'option_c' => ['en' => 'Lantern parade', 'nl' => 'Lampionoptocht', 'hr' => 'Povorka lampiona', 'se' => 'Lyktparad'],
                'option_d' => ['en' => 'Masquerade ball', 'nl' => 'Gemaskerd bal', 'hr' => 'Maskenbal', 'se' => 'Maskerad'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'SE',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "What is the name of Sweden's northernmost significant city, located above the Arctic Circle?", 'nl' => 'Hoe heet de belangrijkste stad van Zweden die het meest noordelijk ligt, boven de poolcirkel?', 'hr' => 'Kako se zove najsjeverniji značajniji grad Švedske, smješten iznad polarnog kruga?', 'se' => 'Vad heter Sveriges viktigaste nordligaste stad, belägen ovanför polcirkeln?'],
                'option_a' => ['en' => 'Kiruna', 'nl' => 'Kiruna', 'hr' => 'Kiruna', 'se' => 'Kiruna'],
                'option_b' => ['en' => 'Umeå', 'nl' => 'Umeå', 'hr' => 'Umeå', 'se' => 'Umeå'],
                'option_c' => ['en' => 'Luleå', 'nl' => 'Luleå', 'hr' => 'Luleå', 'se' => 'Luleå'],
                'option_d' => ['en' => 'Östersund', 'nl' => 'Östersund', 'hr' => 'Östersund', 'se' => 'Östersund'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'SE',
                'difficulty' => 'hard',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function croatiaQuestions(): array
    {
        return [
            [
                'question_text' => ['en' => 'What is the capital of Croatia?', 'nl' => 'Wat is de hoofdstad van Kroatië?', 'hr' => 'Koji je glavni grad Hrvatske?', 'se' => 'Vad är Kroatiens huvudstad?'],
                'option_a' => ['en' => 'Split', 'nl' => 'Split', 'hr' => 'Split', 'se' => 'Split'],
                'option_b' => ['en' => 'Zagreb', 'nl' => 'Zagreb', 'hr' => 'Zagreb', 'se' => 'Zagreb'],
                'option_c' => ['en' => 'Rijeka', 'nl' => 'Rijeka', 'hr' => 'Rijeka', 'se' => 'Rijeka'],
                'option_d' => ['en' => 'Osijek', 'nl' => 'Osijek', 'hr' => 'Osijek', 'se' => 'Osijek'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these does NOT share a land border with Croatia?', 'nl' => 'Welk van deze deelt GEEN landgrens met Kroatië?', 'hr' => 'Koja od ovih država NE dijeli kopnenu granicu s Hrvatskom?', 'se' => 'Vilket av dessa delar INTE landgräns med Kroatien?'],
                'option_a' => ['en' => 'Slovenia', 'nl' => 'Slovenië', 'hr' => 'Slovenija', 'se' => 'Slovenien'],
                'option_b' => ['en' => 'Hungary', 'nl' => 'Hongarije', 'hr' => 'Mađarska', 'se' => 'Ungern'],
                'option_c' => ['en' => 'Serbia', 'nl' => 'Servië', 'hr' => 'Srbija', 'se' => 'Serbien'],
                'option_d' => ['en' => 'Italy', 'nl' => 'Italië', 'hr' => 'Italija', 'se' => 'Italien'],
                'correct_option' => 'D',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is a traditional Croatian food?', 'nl' => 'Welke van deze is een traditioneel Kroatisch gerecht?', 'hr' => 'Koje je od ovoga tradicionalno hrvatsko jelo?', 'se' => 'Vilken av dessa är en traditionell kroatisk maträtt?'],
                'option_a' => ['en' => 'Paella', 'nl' => 'Paella', 'hr' => 'Paella', 'se' => 'Paella'],
                'option_b' => ['en' => 'Ćevapi', 'nl' => 'Ćevapi', 'hr' => 'Ćevapi', 'se' => 'Ćevapi'],
                'option_c' => ['en' => 'Sushi', 'nl' => 'Sushi', 'hr' => 'Sushi', 'se' => 'Sushi'],
                'option_d' => ['en' => 'Tacos', 'nl' => 'Tacos', 'hr' => 'Tacos', 'se' => 'Tacos'],
                'correct_option' => 'B',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which color is NOT on the Croatian flag?', 'nl' => 'Welke kleur staat NIET op de Kroatische vlag?', 'hr' => 'Koja boja NIJE na hrvatskoj zastavi?', 'se' => 'Vilken färg finns INTE på den kroatiska flaggan?'],
                'option_a' => ['en' => 'Red', 'nl' => 'Rood', 'hr' => 'Crvena', 'se' => 'Röd'],
                'option_b' => ['en' => 'White', 'nl' => 'Wit', 'hr' => 'Bijela', 'se' => 'Vit'],
                'option_c' => ['en' => 'Blue', 'nl' => 'Blauw', 'hr' => 'Plava', 'se' => 'Blå'],
                'option_d' => ['en' => 'Green', 'nl' => 'Groen', 'hr' => 'Zelena', 'se' => 'Grön'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'What is "kava" most commonly associated with in Croatia?', 'nl' => 'Waarmee wordt "kava" in Kroatië meestal geassocieerd?', 'hr' => 'S čime se "kava" najčešće povezuje u Hrvatskoj?', 'se' => 'Vad förknippas "kava" oftast med i Kroatien?'],
                'option_a' => ['en' => 'A coffee break / social ritual', 'nl' => 'Een koffiepauze / sociaal ritueel', 'hr' => 'Pauza za kavu / društveni ritual', 'se' => 'Ett kaffeavbrott/socialt ritual'],
                'option_b' => ['en' => 'A national holiday', 'nl' => 'Een nationale feestdag', 'hr' => 'Državni praznik', 'se' => 'En nationell helgdag'],
                'option_c' => ['en' => 'A type of dance', 'nl' => 'Een soort dans', 'hr' => 'Vrsta plesa', 'se' => 'En typ av dans'],
                'option_d' => ['en' => 'A winter sport', 'nl' => 'Een wintersport', 'hr' => 'Zimski sport', 'se' => 'En vintersport'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT a Croatian island?', 'nl' => 'Welk van deze is GEEN Kroatisch eiland?', 'hr' => 'Koji od ovih NIJE hrvatski otok?', 'se' => 'Vilken av dessa är INTE en kroatisk ö?'],
                'option_a' => ['en' => 'Hvar', 'nl' => 'Hvar', 'hr' => 'Hvar', 'se' => 'Hvar'],
                'option_b' => ['en' => 'Brač', 'nl' => 'Brač', 'hr' => 'Brač', 'se' => 'Brač'],
                'option_c' => ['en' => 'Korčula', 'nl' => 'Korčula', 'hr' => 'Korčula', 'se' => 'Korčula'],
                'option_d' => ['en' => 'Capri', 'nl' => 'Capri', 'hr' => 'Capri', 'se' => 'Capri'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which city is a major Adriatic port connected to Italy by regular ferry?', 'nl' => 'Welke stad is een belangrijke Adriatische haven die per veerboot regelmatig met Italië is verbonden?', 'hr' => 'Koji je grad velika jadranska luka povezana s Italijom redovitim trajektom?', 'se' => 'Vilken stad är en stor adriatisk hamn som är förbunden med Italien via reguljär färja?'],
                'option_a' => ['en' => 'Zagreb', 'nl' => 'Zagreb', 'hr' => 'Zagreb', 'se' => 'Zagreb'],
                'option_b' => ['en' => 'Rijeka', 'nl' => 'Rijeka', 'hr' => 'Rijeka', 'se' => 'Rijeka'],
                'option_c' => ['en' => 'Osijek', 'nl' => 'Osijek', 'hr' => 'Osijek', 'se' => 'Osijek'],
                'option_d' => ['en' => 'Varaždin', 'nl' => 'Varaždin', 'hr' => 'Varaždin', 'se' => 'Varaždin'],
                'correct_option' => 'B',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these people is NOT Croatian?', 'nl' => 'Wie van deze personen is NIET Kroatisch?', 'hr' => 'Koja od ovih osoba NIJE Hrvat?', 'se' => 'Vilken av dessa personer är INTE kroat?'],
                'option_a' => ['en' => 'Nikola Tesla', 'nl' => 'Nikola Tesla', 'hr' => 'Nikola Tesla', 'se' => 'Nikola Tesla'],
                'option_b' => ['en' => 'Ruđer Bošković', 'nl' => 'Ruđer Bošković', 'hr' => 'Ruđer Bošković', 'se' => 'Ruđer Bošković'],
                'option_c' => ['en' => 'Marco Polo', 'nl' => 'Marco Polo', 'hr' => 'Marco Polo', 'se' => 'Marco Polo'],
                'option_d' => ['en' => 'Isaac Newton', 'nl' => 'Isaac Newton', 'hr' => 'Isaac Newton', 'se' => 'Isaac Newton'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which of these has been a major political party in Croatian politics?', 'nl' => 'Welke van deze is een belangrijke politieke partij in de Kroatische politiek geweest?', 'hr' => 'Koja je od ovih bila velika politička stranka u hrvatskoj politici?', 'se' => 'Vilket av dessa har varit ett stort politiskt parti i kroatisk politik?'],
                'option_a' => ['en' => 'HDZ', 'nl' => 'HDZ', 'hr' => 'HDZ', 'se' => 'HDZ'],
                'option_b' => ['en' => 'SDP', 'nl' => 'SDP', 'hr' => 'SDP', 'se' => 'SDP'],
                'option_c' => ['en' => 'Most', 'nl' => 'Most', 'hr' => 'Most', 'se' => 'Most'],
                'option_d' => ['en' => 'All of the above', 'nl' => 'Allemaal', 'hr' => 'Sve navedeno', 'se' => 'Alla ovanstående'],
                'correct_option' => 'D',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "Which of these is NOT a common feature of Croatia's landscape?", 'nl' => 'Wat is GEEN veelvoorkomend kenmerk van het Kroatische landschap?', 'hr' => 'Što NIJE uobičajena značajka hrvatskog krajolika?', 'se' => 'Vad är INTE ett vanligt inslag i det kroatiska landskapet?'],
                'option_a' => ['en' => 'Forests', 'nl' => 'Bossen', 'hr' => 'Šume', 'se' => 'Skogar'],
                'option_b' => ['en' => 'Lakes', 'nl' => 'Meren', 'hr' => 'Jezera', 'se' => 'Sjöar'],
                'option_c' => ['en' => 'Mountains', 'nl' => 'Bergen', 'hr' => 'Planine', 'se' => 'Berg'],
                'option_d' => ['en' => 'Deserts', 'nl' => 'Woestijnen', 'hr' => 'Pustinje', 'se' => 'Öknar'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which king is traditionally considered the first king of Croatia?', 'nl' => 'Welke koning wordt traditioneel beschouwd als de eerste koning van Kroatië?', 'hr' => 'Koji se kralj tradicionalno smatra prvim hrvatskim kraljem?', 'se' => 'Vilken kung anses traditionellt vara Kroatiens förste kung?'],
                'option_a' => ['en' => 'Tomislav', 'nl' => 'Tomislav', 'hr' => 'Tomislav', 'se' => 'Tomislav'],
                'option_b' => ['en' => 'Zvonimir', 'nl' => 'Zvonimir', 'hr' => 'Zvonimir', 'se' => 'Zvonimir'],
                'option_c' => ['en' => 'Petar Krešimir IV', 'nl' => 'Petar Krešimir IV', 'hr' => 'Petar Krešimir IV', 'se' => 'Petar Krešimir IV'],
                'option_d' => ['en' => 'Petar Svačić', 'nl' => 'Petar Svačić', 'hr' => 'Petar Svačić', 'se' => 'Petar Svačić'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these territories were historically significant parts of the Croatian lands?', 'nl' => 'Welke van deze gebieden waren historisch belangrijke delen van de Kroatische landen?', 'hr' => 'Koja su od ovih područja povijesno bila značajni dijelovi hrvatskih zemalja?', 'se' => 'Vilka av dessa territorier var historiskt viktiga delar av de kroatiska länderna?'],
                'option_a' => ['en' => 'Dalmatia', 'nl' => 'Dalmatië', 'hr' => 'Dalmacija', 'se' => 'Dalmatien'],
                'option_b' => ['en' => 'Slavonia', 'nl' => 'Slavonië', 'hr' => 'Slavonija', 'se' => 'Slavonien'],
                'option_c' => ['en' => 'Istria', 'nl' => 'Istrië', 'hr' => 'Istra', 'se' => 'Istrien'],
                'option_d' => ['en' => 'All of the above', 'nl' => 'Allemaal', 'hr' => 'Sve navedeno', 'se' => 'Alla ovanstående'],
                'correct_option' => 'D',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => "What is Croatia's highest mountain?", 'nl' => 'Wat is de hoogste berg van Kroatië?', 'hr' => 'Koja je najviša planina Hrvatske?', 'se' => 'Vilket är Kroatiens högsta berg?'],
                'option_a' => ['en' => 'Dinara', 'nl' => 'Dinara', 'hr' => 'Dinara', 'se' => 'Dinara'],
                'option_b' => ['en' => 'Velebit', 'nl' => 'Velebit', 'hr' => 'Velebit', 'se' => 'Velebit'],
                'option_c' => ['en' => 'Biokovo', 'nl' => 'Biokovo', 'hr' => 'Biokovo', 'se' => 'Biokovo'],
                'option_d' => ['en' => 'Risnjak', 'nl' => 'Risnjak', 'hr' => 'Risnjak', 'se' => 'Risnjak'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which of these is NOT located in Croatia?', 'nl' => 'Welk van deze ligt NIET in Kroatië?', 'hr' => 'Koje se od ovoga NE nalazi u Hrvatskoj?', 'se' => 'Vilken av dessa ligger INTE i Kroatien?'],
                'option_a' => ['en' => 'Vransko Lake', 'nl' => 'Vransko meer', 'hr' => 'Vransko jezero', 'se' => 'Vransjön'],
                'option_b' => ['en' => 'Plitvice Lakes', 'nl' => 'Plitvicemeren', 'hr' => 'Plitvička jezera', 'se' => 'Plitvicesjöarna'],
                'option_c' => ['en' => 'Lake Peruća', 'nl' => 'Peruća-meer', 'hr' => 'Peručko jezero', 'se' => 'Peručasjön'],
                'option_d' => ['en' => 'Lake Geneva', 'nl' => 'Meer van Genève', 'hr' => 'Ženevsko jezero', 'se' => 'Genèvesjön'],
                'correct_option' => 'D',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'In which year did Croatia declare independence from Yugoslavia?', 'nl' => 'In welk jaar verklaarde Kroatië zich onafhankelijk van Joegoslavië?', 'hr' => 'Koje je godine Hrvatska proglasila neovisnost od Jugoslavije?', 'se' => 'Vilket år förklarade Kroatien sin självständighet från Jugoslavien?'],
                'option_a' => ['en' => '1989', 'nl' => '1989', 'hr' => '1989', 'se' => '1989'],
                'option_b' => ['en' => '1991', 'nl' => '1991', 'hr' => '1991', 'se' => '1991'],
                'option_c' => ['en' => '1995', 'nl' => '1995', 'hr' => '1995', 'se' => '1995'],
                'option_d' => ['en' => '2000', 'nl' => '2000', 'hr' => '2000', 'se' => '2000'],
                'correct_option' => 'B',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which sea borders Croatia?', 'nl' => 'Welke zee grenst aan Kroatië?', 'hr' => 'Koje more graniči s Hrvatskom?', 'se' => 'Vilket hav gränsar till Kroatien?'],
                'option_a' => ['en' => 'Adriatic Sea', 'nl' => 'Adriatische Zee', 'hr' => 'Jadransko more', 'se' => 'Adriatiska havet'],
                'option_b' => ['en' => 'Baltic Sea', 'nl' => 'Oostzee', 'hr' => 'Baltičko more', 'se' => 'Östersjön'],
                'option_c' => ['en' => 'Black Sea', 'nl' => 'Zwarte Zee', 'hr' => 'Crno more', 'se' => 'Svarta havet'],
                'option_d' => ['en' => 'North Sea', 'nl' => 'Noordzee', 'hr' => 'Sjeverno more', 'se' => 'Nordsjön'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => "What is Croatia's official currency?", 'nl' => 'Wat is de officiële munteenheid van Kroatië?', 'hr' => 'Koja je službena valuta Hrvatske?', 'se' => 'Vad är Kroatiens officiella valuta?'],
                'option_a' => ['en' => 'Euro', 'nl' => 'Euro', 'hr' => 'Euro', 'se' => 'Euro'],
                'option_b' => ['en' => 'Kuna', 'nl' => 'Kuna', 'hr' => 'Kuna', 'se' => 'Kuna'],
                'option_c' => ['en' => 'Lira', 'nl' => 'Lira', 'hr' => 'Lira', 'se' => 'Lira'],
                'option_d' => ['en' => 'Dinar', 'nl' => 'Dinar', 'hr' => 'Dinar', 'se' => 'Dinar'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Croatian city is known as the "Pearl of the Adriatic"?', 'nl' => 'Welke Kroatische stad staat bekend als de "Parel van de Adriatische Zee"?', 'hr' => 'Koji je hrvatski grad poznat kao "Biser Jadrana"?', 'se' => 'Vilken kroatisk stad är känd som "Adriatiska havets pärla"?'],
                'option_a' => ['en' => 'Dubrovnik', 'nl' => 'Dubrovnik', 'hr' => 'Dubrovnik', 'se' => 'Dubrovnik'],
                'option_b' => ['en' => 'Split', 'nl' => 'Split', 'hr' => 'Split', 'se' => 'Split'],
                'option_c' => ['en' => 'Zadar', 'nl' => 'Zadar', 'hr' => 'Zadar', 'se' => 'Zadar'],
                'option_d' => ['en' => 'Pula', 'nl' => 'Pula', 'hr' => 'Pula', 'se' => 'Pula'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'Which Croatian national park is famous for its terraced lakes and waterfalls?', 'nl' => 'Welk Kroatisch nationaal park is beroemd om zijn trapsgewijze meren en watervallen?', 'hr' => 'Koji je hrvatski nacionalni park poznat po jezerima na terasama i vodopadima?', 'se' => 'Vilken kroatisk nationalpark är känd för sina terrasserade sjöar och vattenfall?'],
                'option_a' => ['en' => 'Plitvice Lakes National Park', 'nl' => 'Nationaal park Plitvicemeren', 'hr' => 'Nacionalni park Plitvička jezera', 'se' => 'Nationalparken Plitvicesjöarna'],
                'option_b' => ['en' => 'Serengeti National Park', 'nl' => 'Nationaal park Serengeti', 'hr' => 'Nacionalni park Serengeti', 'se' => 'Serengeti nationalpark'],
                'option_c' => ['en' => 'Yosemite National Park', 'nl' => 'Nationaal park Yosemite', 'hr' => 'Nacionalni park Yosemite', 'se' => 'Yosemite nationalpark'],
                'option_d' => ['en' => 'Fjordland National Park', 'nl' => 'Nationaal park Fjordland', 'hr' => 'Nacionalni park Fjordland', 'se' => 'Fjordland nationalpark'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Roman emperor was born near Split and built a famous palace there?', 'nl' => 'Welke Romeinse keizer werd geboren nabij Split en bouwde daar een beroemd paleis?', 'hr' => 'Koji je rimski car rođen u blizini Splita i tamo izgradio poznatu palaču?', 'se' => 'Vilken romersk kejsare föddes nära Split och byggde ett berömt palats där?'],
                'option_a' => ['en' => 'Diocletian', 'nl' => 'Diocletianus', 'hr' => 'Dioklecijan', 'se' => 'Diocletianus'],
                'option_b' => ['en' => 'Julius Caesar', 'nl' => 'Julius Caesar', 'hr' => 'Julije Cezar', 'se' => 'Julius Caesar'],
                'option_c' => ['en' => 'Nero', 'nl' => 'Nero', 'hr' => 'Neron', 'se' => 'Nero'],
                'option_d' => ['en' => 'Constantine', 'nl' => 'Constantijn', 'hr' => 'Konstantin', 'se' => 'Konstantin'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which everyday item of clothing is said to derive its name from Croatian soldiers ("Hrvat")?', 'nl' => 'Van welk alledaags kledingstuk wordt gezegd dat het zijn naam ontleent aan Kroatische soldaten ("Hrvat")?', 'hr' => 'Za koji se svakodnevni odjevni predmet kaže da izvodi svoje ime od hrvatskih vojnika ("Hrvat")?', 'se' => 'Vilket vardagligt klädesplagg sägs ha fått sitt namn från kroatiska soldater ("Hrvat")?'],
                'option_a' => ['en' => 'The necktie (cravat)', 'nl' => 'De das (cravate)', 'hr' => 'Kravata', 'se' => 'Slipsen (kravatt)'],
                'option_b' => ['en' => 'The umbrella', 'nl' => 'De paraplu', 'hr' => 'Kišobran', 'se' => 'Paraplyn'],
                'option_c' => ['en' => 'The wristwatch', 'nl' => 'Het polshorloge', 'hr' => 'Ručni sat', 'se' => 'Armbandsuret'],
                'option_d' => ['en' => 'The button', 'nl' => 'De knoop', 'hr' => 'Gumb', 'se' => 'Knappen'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which Croatian peninsula region is known for truffles and wine?', 'nl' => 'Welk Kroatisch schiereilandgebied staat bekend om truffels en wijn?', 'hr' => 'Koja je hrvatska poluotočna regija poznata po tartufima i vinu?', 'se' => 'Vilken kroatisk halvöregion är känd för tryffel och vin?'],
                'option_a' => ['en' => 'Istria', 'nl' => 'Istrië', 'hr' => 'Istra', 'se' => 'Istrien'],
                'option_b' => ['en' => 'Slavonia', 'nl' => 'Slavonië', 'hr' => 'Slavonija', 'se' => 'Slavonien'],
                'option_c' => ['en' => 'Dalmatia', 'nl' => 'Dalmatië', 'hr' => 'Dalmacija', 'se' => 'Dalmatien'],
                'option_d' => ['en' => 'Zagorje', 'nl' => 'Zagorje', 'hr' => 'Zagorje', 'se' => 'Zagorje'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Croatia was a republic within which federation from 1945 to 1991?', 'nl' => 'Kroatië was van 1945 tot 1991 een republiek binnen welke federatie?', 'hr' => 'Hrvatska je od 1945. do 1991. bila republika u sastavu koje federacije?', 'se' => 'Kroatien var en republik inom vilken federation från 1945 till 1991?'],
                'option_a' => ['en' => 'Yugoslavia', 'nl' => 'Joegoslavië', 'hr' => 'Jugoslavija', 'se' => 'Jugoslavien'],
                'option_b' => ['en' => 'Soviet Union', 'nl' => 'Sovjet-Unie', 'hr' => 'Sovjetski Savez', 'se' => 'Sovjetunionen'],
                'option_c' => ['en' => 'Austro-Hungarian Empire', 'nl' => 'Oostenrijk-Hongarije', 'hr' => 'Austro-Ugarska', 'se' => 'Österrike-Ungern'],
                'option_d' => ['en' => 'Ottoman Empire', 'nl' => 'Ottomaanse Rijk', 'hr' => 'Osmansko Carstvo', 'se' => 'Osmanska riket'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'Which Croatian tennis player won the Wimbledon singles title in 2001?', 'nl' => 'Welke Kroatische tennisser won in 2001 de Wimbledon-titel in het enkelspel?', 'hr' => 'Koji je hrvatski tenisač osvojio naslov na Wimbledonu u pojedinačnoj konkurenciji 2001. godine?', 'se' => 'Vilken kroatisk tennisspelare vann Wimbledons singeltitel 2001?'],
                'option_a' => ['en' => 'Goran Ivanišević', 'nl' => 'Goran Ivanišević', 'hr' => 'Goran Ivanišević', 'se' => 'Goran Ivanišević'],
                'option_b' => ['en' => 'Rafael Nadal', 'nl' => 'Rafael Nadal', 'hr' => 'Rafael Nadal', 'se' => 'Rafael Nadal'],
                'option_c' => ['en' => 'Novak Djokovic', 'nl' => 'Novak Djokovic', 'hr' => 'Novak Đoković', 'se' => 'Novak Djokovic'],
                'option_d' => ['en' => 'Roger Federer', 'nl' => 'Roger Federer', 'hr' => 'Roger Federer', 'se' => 'Roger Federer'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => 'What are the famous waterfalls on the Krka river known as?', 'nl' => 'Hoe worden de beroemde watervallen aan de rivier de Krka genoemd?', 'hr' => 'Kako se zovu poznati vodopadi na rijeci Krki?', 'se' => 'Vad kallas de berömda vattenfallen vid floden Krka?'],
                'option_a' => ['en' => 'Skradinski Buk', 'nl' => 'Skradinski Buk', 'hr' => 'Skradinski buk', 'se' => 'Skradinski Buk'],
                'option_b' => ['en' => 'Niagara Falls', 'nl' => 'Niagara-watervallen', 'hr' => 'Niagarini slapovi', 'se' => 'Niagarafallen'],
                'option_c' => ['en' => 'Victoria Falls', 'nl' => 'Victoriawatervallen', 'hr' => 'Viktorijini slapovi', 'se' => 'Victoriafallen'],
                'option_d' => ['en' => 'Angel Falls', 'nl' => 'Angel Falls', 'hr' => 'Anđeoski slapovi', 'se' => 'Angel Falls'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
            [
                'question_text' => ['en' => "What is Croatia's largest island by area?", 'nl' => 'Wat is het grootste eiland van Kroatië qua oppervlakte?', 'hr' => 'Koji je najveći hrvatski otok po površini?', 'se' => 'Vilken är Kroatiens största ö till ytan?'],
                'option_a' => ['en' => 'Cres', 'nl' => 'Cres', 'hr' => 'Cres', 'se' => 'Cres'],
                'option_b' => ['en' => 'Krk', 'nl' => 'Krk', 'hr' => 'Krk', 'se' => 'Krk'],
                'option_c' => ['en' => 'Hvar', 'nl' => 'Hvar', 'hr' => 'Hvar', 'se' => 'Hvar'],
                'option_d' => ['en' => 'Brač', 'nl' => 'Brač', 'hr' => 'Brač', 'se' => 'Brač'],
                'correct_option' => 'A',
                'category' => 'Geography',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => "In which year did Croatia's football team reach the FIFA World Cup final for the first time?", 'nl' => 'In welk jaar bereikte het Kroatische voetbalelftal voor het eerst de finale van het WK voetbal?', 'hr' => 'Koje je godine hrvatska nogometna reprezentacija prvi put došla do finala Svjetskog prvenstva?', 'se' => 'Vilket år nådde Kroatiens fotbollslandslag för första gången VM-finalen?'],
                'option_a' => ['en' => '2018', 'nl' => '2018', 'hr' => '2018', 'se' => '2018'],
                'option_b' => ['en' => '2014', 'nl' => '2014', 'hr' => '2014', 'se' => '2014'],
                'option_c' => ['en' => '2010', 'nl' => '2010', 'hr' => '2010', 'se' => '2010'],
                'option_d' => ['en' => '2022', 'nl' => '2022', 'hr' => '2022', 'se' => '2022'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'easy',
            ],
            [
                'question_text' => ['en' => 'In which year did Croatia become a member of the European Union?', 'nl' => 'In welk jaar werd Kroatië lid van de Europese Unie?', 'hr' => 'Koje je godine Hrvatska postala članica Europske unije?', 'se' => 'Vilket år blev Kroatien medlem i Europeiska unionen?'],
                'option_a' => ['en' => '2013', 'nl' => '2013', 'hr' => '2013', 'se' => '2013'],
                'option_b' => ['en' => '2009', 'nl' => '2009', 'hr' => '2009', 'se' => '2009'],
                'option_c' => ['en' => '2004', 'nl' => '2004', 'hr' => '2004', 'se' => '2004'],
                'option_d' => ['en' => '2016', 'nl' => '2016', 'hr' => '2016', 'se' => '2016'],
                'correct_option' => 'A',
                'category' => 'History',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Paklenica National Park lies within which Croatian mountain range?', 'nl' => 'In welk Kroatisch gebergte ligt Nationaal park Paklenica?', 'hr' => 'U kojem se hrvatskom planinskom lancu nalazi Nacionalni park Paklenica?', 'se' => 'Inom vilken kroatisk bergskedja ligger nationalparken Paklenica?'],
                'option_a' => ['en' => 'Velebit', 'nl' => 'Velebit', 'hr' => 'Velebit', 'se' => 'Velebit'],
                'option_b' => ['en' => 'Dinara', 'nl' => 'Dinara', 'hr' => 'Dinara', 'se' => 'Dinara'],
                'option_c' => ['en' => 'Biokovo', 'nl' => 'Biokovo', 'hr' => 'Biokovo', 'se' => 'Biokovo'],
                'option_d' => ['en' => 'Risnjak', 'nl' => 'Risnjak', 'hr' => 'Risnjak', 'se' => 'Risnjak'],
                'correct_option' => 'A',
                'category' => 'Nature',
                'country' => 'HR',
                'difficulty' => 'medium',
            ],
            [
                'question_text' => ['en' => 'Which currency did Croatia adopt in January 2023, replacing the kuna?', 'nl' => 'Welke munteenheid nam Kroatië in januari 2023 aan ter vervanging van de kuna?', 'hr' => 'Koju je valutu Hrvatska uvela u siječnju 2023., zamijenivši kunu?', 'se' => 'Vilken valuta antog Kroatien i januari 2023, som ersatte kunan?'],
                'option_a' => ['en' => 'Euro', 'nl' => 'Euro', 'hr' => 'Euro', 'se' => 'Euro'],
                'option_b' => ['en' => 'Dollar', 'nl' => 'Dollar', 'hr' => 'Dolar', 'se' => 'Dollar'],
                'option_c' => ['en' => 'Franc', 'nl' => 'Frank', 'hr' => 'Franak', 'se' => 'Franc'],
                'option_d' => ['en' => 'Lira', 'nl' => 'Lira', 'hr' => 'Lira', 'se' => 'Lira'],
                'correct_option' => 'A',
                'category' => 'Culture',
                'country' => 'HR',
                'difficulty' => 'hard',
            ],
        ];
    }
}
